# Fast Track to Julia NoteBook

Expanding on parts of [Fast Track to Julia](https://juliadocs.github.io/Julia-Cheat-Sheet/)

## Basics

In [50]:
a = 2.5
5a

12.5

In [51]:
5*a

12.5

`ans` has the result from the last calculation:

In [52]:
ans

12.5

### Two types of comments 

#### Frist type:

In [53]:
# this is a one line comment
9a # comment can be at the end of a line too

22.5

#### Second type:

In [54]:
#= This is the first line of a comment block
9a # comment can be at the end of a line too
This is the last line of the block =# 

### Julia allows simple way to swap values of variables

In [55]:
a,b = 1,2
[a,b]

2-element Array{Int64,1}:
 1
 2

In [56]:
# easy swapping of values
a,b = b,a
[a,b]

2-element Array{Int64,1}:
 2
 1

In [57]:
# in most languages you have to do
a = 1
b = 2
temp = a
a = b
b = temp
[a,b]

2-element Array{Int64,1}:
 2
 1

### Julia allows simple boolean expressions

In [58]:
# Example
1 < a < 3

true

In [59]:
# In many languages this has to be written as
1 < a && a < 3

true

### Ternary Operator

In [60]:
a = 1
b = 1
c = 2

res = a==b ? a : b

1

In [61]:
a==c ? a : c

2

In [62]:
a==c ? 1 : 10

10

In [63]:
a==c-b ? 1 : 10

1

### Remainder

In [64]:
99 % 10

9

In [65]:
100 % 10

0

In [66]:
90 % 10

0

## Arrays (Vectors and Matricies)

### Declaration and Initialization of arrays

In [67]:
# empty vector of double precision floats
v = Array{Float64,1}()

0-element Array{Float64,1}

In [68]:
push!(v,2.0)
v

1-element Array{Float64,1}:
 2.0

In [69]:
# vector of size 5, double precision floats
u =  Array{Float64,1}(undef, 5)

5-element Array{Float64,1}:
 2.54639494965e-313
 2.75859452875e-313
 1.27319747527e-313
 6.5781869533e-313 
 2.1219958073e-314 

In [259]:
# matrix of size 3x5, double precision floats
U =  Array{Float64,2}(undef, 3,5)

3×5 Array{Float64,2}:
 NaN            6.94962e-310  6.94962e-310  6.94965e-310  6.94962e-310
   0.0          6.94962e-310  3.45846e-323  6.94962e-310  6.94962e-310
   1.4822e-323  6.94962e-310  2.96439e-323  0.0           6.94962e-310

In [71]:
# vector of size 5, of 2.2
u =  fill(2.2,5)

5-element Array{Float64,1}:
 2.2
 2.2
 2.2
 2.2
 2.2

In [72]:
zeros(5)

5-element Array{Float64,1}:
 0.0
 0.0
 0.0
 0.0
 0.0

In [73]:
zeros(3,5)

3×5 Array{Float64,2}:
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0

In [74]:
zero(U)

3×5 Array{Float64,2}:
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0

In [75]:
ones(3,5)

3×5 Array{Float64,2}:
 1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0

In [76]:
using Random, Statistics

In [77]:
rand(3,5) # uniform(0,1)

3×5 Array{Float64,2}:
 0.166479  0.268334  0.269063  0.605399  0.642119
 0.722327  0.67564   0.882251  0.183593  0.70494 
 0.810225  0.798755  0.806262  0.593992  0.201726

In [78]:
randn(3,5) # standard normal

3×5 Array{Float64,2}:
 0.788536  -0.309659    0.81292   1.5094     0.717494
 0.289554  -0.00780053  1.25038   0.881649  -0.765373
 1.15377   -1.83402     0.132648  0.254369  -2.46029 

In [79]:
mean(randn(1_000_000))

-0.0005147259950349833

In [80]:
var(randn(1_000_000))

0.9986005256080187

In [3]:
using Distributions, LinearAlgebra

In [4]:
M = rand(Binomial(2,0.5),10,20)

10×20 Array{Int64,2}:
 1  0  0  2  0  0  1  2  1  2  2  2  0  2  1  1  0  2  0  1
 1  2  1  1  2  1  1  1  2  1  1  0  2  1  1  2  1  1  1  0
 0  1  0  2  1  1  0  2  2  1  2  0  1  0  2  1  1  1  1  1
 0  1  1  0  1  2  2  0  2  1  0  0  2  2  1  1  0  0  2  0
 0  1  0  1  0  0  0  1  0  1  1  0  2  0  1  1  2  1  1  1
 2  1  2  1  0  1  2  2  0  1  2  1  2  2  2  2  1  0  1  0
 2  1  1  1  1  1  0  1  1  1  1  0  1  1  1  0  1  0  0  0
 1  0  0  1  1  1  2  1  0  1  0  1  0  1  0  1  0  1  1  1
 0  2  2  2  0  1  2  0  0  1  1  1  2  1  0  2  1  2  1  0
 0  2  2  0  2  1  1  1  0  1  1  1  0  1  0  1  0  1  1  1

#### Get first column as one dimensionsal array

In [5]:
M[:,1]

10-element Array{Int64,1}:
 1
 1
 0
 0
 0
 2
 2
 1
 0
 0

#### Get first row as one dimensionsal array¶

In [6]:
M[1,:]

20-element Array{Int64,1}:
 1
 0
 0
 2
 0
 0
 1
 2
 1
 2
 2
 2
 0
 2
 1
 1
 0
 2
 0
 1

#### Transposing and array gives a row vector 

In [7]:
M[1,:]'

1×20 Adjoint{Int64,Array{Int64,1}}:
 1  0  0  2  0  0  1  2  1  2  2  2  0  2  1  1  0  2  0  1

#### Sum of squares of elements in first row

In [8]:
M[1,:]'M[1,:]

34

In [9]:
M[1,:]'*M[1,:]

34

In [10]:
dot(M[1,:],M[1,:])

34

In [11]:
M[1,:].^2

20-element Array{Int64,1}:
 1
 0
 0
 4
 0
 0
 1
 4
 1
 4
 4
 4
 0
 4
 1
 1
 0
 4
 0
 1

In [12]:
sum(M[1,:].^2)

34

#### Matrix transpose and product 

In [13]:
M'M == M'*M

true

### Identity Matrix

#### In general

In [14]:
Matrix{Float64}(I,3,3)

3×3 Array{Float64,2}:
 1.0  0.0  0.0
 0.0  1.0  0.0
 0.0  0.0  1.0

In [15]:
Matrix{Float64}(I,3,4)

3×4 Array{Float64,2}:
 1.0  0.0  0.0  0.0
 0.0  1.0  0.0  0.0
 0.0  0.0  1.0  0.0

In [16]:
Matrix{Float64}(I,4,3)

4×3 Array{Float64,2}:
 1.0  0.0  0.0
 0.0  1.0  0.0
 0.0  0.0  1.0
 0.0  0.0  0.0

#### When dimensions can be inferred

In [17]:
A = M'M + I

20×20 Array{Int64,2}:
 12   6   7   8   5   6   8  10   5   8   9  5   8  10   8   8   5   4   4  2
  6  18  14  11  11  11  12  10   9  11  12  5  16  11   9  15   9  10  11  4
  7  14  16   8   8  10  13   8   5   9  10  6  13  12   7  13   6   7   9  2
  8  11   8  18   6   8  11  14   9  13  15  8  13  11  11  14   9  13   8  6
  5  11   8   6  13   9   8   8   9   8   7  3   8   8   6   9   4   6   8  4
  6  11  10   8   9  12  12   8   9   9   8  4  12  11   8  11   5   6  10  3
  8  12  13  11   8  12  20  10   7  12  10  9  14  16   8  16   5  10  12  4
 10  10   8  14   8   8  10  18   9  13  16  8  11  12  13  13   8  10   8  7
  5   9   5   9   9   9   7   9  15   9   9  2  11   9  10   9   5   6   8  3
  8  11   9  13   8   9  12  13   9  14  13  8  12  13  10  13   7  11   9  6
  9  12  10  15   7   8  10  16   9  13  18  8  13  12  13  14   9  11   8  6
  5   5   6   8   3   4   9   8   2   8   8  9   4   9   4   8   2   8   4  4
  8  16  13  13   8  12  14  11  11  12  1

### Diagonal Matrix from $\mathbf{A}$

In [18]:
Diagonal(A)

20×20 Diagonal{Int64,Array{Int64,1}}:
 12   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅  ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅  ⋅
  ⋅  18   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅  ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅  ⋅
  ⋅   ⋅  16   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅  ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅  ⋅
  ⋅   ⋅   ⋅  18   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅  ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅  ⋅
  ⋅   ⋅   ⋅   ⋅  13   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅  ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅  ⋅
  ⋅   ⋅   ⋅   ⋅   ⋅  12   ⋅   ⋅   ⋅   ⋅   ⋅  ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅  ⋅
  ⋅   ⋅   ⋅   ⋅   ⋅   ⋅  20   ⋅   ⋅   ⋅   ⋅  ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅  ⋅
  ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅  18   ⋅   ⋅   ⋅  ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅  ⋅
  ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅  15   ⋅   ⋅  ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅  ⋅
  ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅  14   ⋅  ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅  ⋅
  ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅  18  ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅  ⋅
  ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅  9   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅  ⋅
  ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   

### Subset of Matrix

In [19]:
B = A[1:2,3:4]

2×2 Array{Int64,2}:
  7   8
 14  11

In [20]:
C = A[1:2,11:end]

2×10 Array{Int64,2}:
  9  5   8  10  8   8  5   4   4  2
 12  5  16  11  9  15  9  10  11  4

### Concatenation
#### Horizontal

In [21]:
[B C]

2×12 Array{Int64,2}:
  7   8   9  5   8  10  8   8  5   4   4  2
 14  11  12  5  16  11  9  15  9  10  11  4

In [22]:
hcat(B,C)

2×12 Array{Int64,2}:
  7   8   9  5   8  10  8   8  5   4   4  2
 14  11  12  5  16  11  9  15  9  10  11  4

#### Vertical

In [23]:
[ 
A[1:2,:]
A[11:end,:]
]

12×20 Array{Int64,2}:
 12   6   7   8   5   6   8  10   5   8   9  5   8  10   8   8   5   4   4  2
  6  18  14  11  11  11  12  10   9  11  12  5  16  11   9  15   9  10  11  4
  9  12  10  15   7   8  10  16   9  13  18  8  13  12  13  14   9  11   8  6
  5   5   6   8   3   4   9   8   2   8   8  9   4   9   4   8   2   8   4  4
  8  16  13  13   8  12  14  11  11  12  13  4  23  13  13  17  12   9  13  3
 10  11  12  11   8  11  16  12   9  13  12  9  13  18  10  14   5   9  10  4
  8   9   7  11   6   8   8  13  10  10  13  4  13  10  14  11   8   6   8  4
  8  15  13  14   9  11  16  13   9  13  14  8  17  14  11  19   9  12  12  5
  5   9   6   9   4   5   5   8   5   7   9  2  12   5   8   9  10   6   6  3
  4  10   7  13   6   6  10  10   6  11  11  8   9   9   6  12   6  14   7  6
  4  11   9   8   8  10  12   8   8   9   8  4  13  10   8  12   6   7  12  4
  2   4   2   6   4   3   4   7   3   6   6  4   3   4   4   5   3   6   4  6

In [24]:
vcat(A[1:2,:],A[11:end,:])

12×20 Array{Int64,2}:
 12   6   7   8   5   6   8  10   5   8   9  5   8  10   8   8   5   4   4  2
  6  18  14  11  11  11  12  10   9  11  12  5  16  11   9  15   9  10  11  4
  9  12  10  15   7   8  10  16   9  13  18  8  13  12  13  14   9  11   8  6
  5   5   6   8   3   4   9   8   2   8   8  9   4   9   4   8   2   8   4  4
  8  16  13  13   8  12  14  11  11  12  13  4  23  13  13  17  12   9  13  3
 10  11  12  11   8  11  16  12   9  13  12  9  13  18  10  14   5   9  10  4
  8   9   7  11   6   8   8  13  10  10  13  4  13  10  14  11   8   6   8  4
  8  15  13  14   9  11  16  13   9  13  14  8  17  14  11  19   9  12  12  5
  5   9   6   9   4   5   5   8   5   7   9  2  12   5   8   9  10   6   6  3
  4  10   7  13   6   6  10  10   6  11  11  8   9   9   6  12   6  14   7  6
  4  11   9   8   8  10  12   8   8   9   8  4  13  10   8  12   6   7  12  4
  2   4   2   6   4   3   4   7   3   6   6  4   3   4   4   5   3   6   4  6

### Sorting

In [25]:
sort(M[:,1])

10-element Array{Int64,1}:
 0
 0
 0
 0
 0
 1
 1
 1
 2
 2

In [26]:
index = sortperm(M[:,1])

10-element Array{Int64,1}:
  3
  4
  5
  9
 10
  1
  2
  8
  6
  7

In [27]:
M[index,1]

10-element Array{Int64,1}:
 0
 0
 0
 0
 0
 1
 1
 1
 2
 2

### Sorting the entire matrix by the first column

In [28]:
M[index,:]

10×20 Array{Int64,2}:
 0  1  0  2  1  1  0  2  2  1  2  0  1  0  2  1  1  1  1  1
 0  1  1  0  1  2  2  0  2  1  0  0  2  2  1  1  0  0  2  0
 0  1  0  1  0  0  0  1  0  1  1  0  2  0  1  1  2  1  1  1
 0  2  2  2  0  1  2  0  0  1  1  1  2  1  0  2  1  2  1  0
 0  2  2  0  2  1  1  1  0  1  1  1  0  1  0  1  0  1  1  1
 1  0  0  2  0  0  1  2  1  2  2  2  0  2  1  1  0  2  0  1
 1  2  1  1  2  1  1  1  2  1  1  0  2  1  1  2  1  1  1  0
 1  0  0  1  1  1  2  1  0  1  0  1  0  1  0  1  0  1  1  1
 2  1  2  1  0  1  2  2  0  1  2  1  2  2  2  2  1  0  1  0
 2  1  1  1  1  1  0  1  1  1  1  0  1  1  1  0  1  0  0  0

### Sorting matrix by the sum of columns 1 and 2

In [29]:
M[sortperm( M[:,1]+M[:,2] ),:]

10×20 Array{Int64,2}:
 1  0  0  2  0  0  1  2  1  2  2  2  0  2  1  1  0  2  0  1
 0  1  0  2  1  1  0  2  2  1  2  0  1  0  2  1  1  1  1  1
 0  1  1  0  1  2  2  0  2  1  0  0  2  2  1  1  0  0  2  0
 0  1  0  1  0  0  0  1  0  1  1  0  2  0  1  1  2  1  1  1
 1  0  0  1  1  1  2  1  0  1  0  1  0  1  0  1  0  1  1  1
 0  2  2  2  0  1  2  0  0  1  1  1  2  1  0  2  1  2  1  0
 0  2  2  0  2  1  1  1  0  1  1  1  0  1  0  1  0  1  1  1
 1  2  1  1  2  1  1  1  2  1  1  0  2  1  1  2  1  1  1  0
 2  1  2  1  0  1  2  2  0  1  2  1  2  2  2  2  1  0  1  0
 2  1  1  1  1  1  0  1  1  1  1  0  1  1  1  0  1  0  0  0

### Selecting rows or columns of matrix

#### Select rows where row sum is > 19

In [30]:
vec(sum(M,dims=2) .> 19)

10-element BitArray{1}:
  true
  true
  true
 false
 false
  true
 false
 false
  true
 false

In [31]:
M[vec(sum(M,dims=2) .> 19), :]

5×20 Array{Int64,2}:
 1  0  0  2  0  0  1  2  1  2  2  2  0  2  1  1  0  2  0  1
 1  2  1  1  2  1  1  1  2  1  1  0  2  1  1  2  1  1  1  0
 0  1  0  2  1  1  0  2  2  1  2  0  1  0  2  1  1  1  1  1
 2  1  2  1  0  1  2  2  0  1  2  1  2  2  2  2  1  0  1  0
 0  2  2  2  0  1  2  0  0  1  1  1  2  1  0  2  1  2  1  0

#### Get random subset of 5 columns from M

In [32]:
sel = sample(1:size(M,2),5,replace=false)

5-element Array{Int64,1}:
 19
  3
 15
  9
  8

In [33]:
M[:,sel]

10×5 Array{Int64,2}:
 0  0  1  1  2
 1  1  1  2  1
 1  0  2  2  2
 2  1  1  2  0
 1  0  1  0  1
 1  2  2  0  2
 0  1  1  1  1
 1  0  0  0  1
 1  2  0  0  0
 1  2  0  0  1

#### Get the remaining columns: 
#### M[:,-sel] does not work in Julia

In [34]:
setdiff(1:size(M,2),sel)

15-element Array{Int64,1}:
  1
  2
  4
  5
  6
  7
 10
 11
 12
 13
 14
 16
 17
 18
 20

In [35]:
M[:,setdiff(1:size(M,2),sel)] # not as nice as M[:,-sel]

10×15 Array{Int64,2}:
 1  0  2  0  0  1  2  2  2  0  2  1  0  2  1
 1  2  1  2  1  1  1  1  0  2  1  2  1  1  0
 0  1  2  1  1  0  1  2  0  1  0  1  1  1  1
 0  1  0  1  2  2  1  0  0  2  2  1  0  0  0
 0  1  1  0  0  0  1  1  0  2  0  1  2  1  1
 2  1  1  0  1  2  1  2  1  2  2  2  1  0  0
 2  1  1  1  1  0  1  1  0  1  1  0  1  0  0
 1  0  1  1  1  2  1  0  1  0  1  1  0  1  1
 0  2  2  0  1  2  1  1  1  2  1  2  1  2  0
 0  2  0  2  1  1  1  1  1  0  1  1  0  1  1

### Copy of array

In [36]:
v = [1, 2, 3]

3-element Array{Int64,1}:
 1
 2
 3

In [37]:
u = v
u[1] = 10
u

3-element Array{Int64,1}:
 10
  2
  3

In [38]:
v

3-element Array{Int64,1}:
 10
  2
  3

##### So, u is not just a copy of v. It is another name for v. To get a copy use:

In [39]:
v = [1, 2, 3]
u = copy(v)
u[1] = 10
u

3-element Array{Int64,1}:
 10
  2
  3

In [40]:
v

3-element Array{Int64,1}:
 1
 2
 3

## Control Flow and Loops

##### Consider adding the vectors u and v. One way to do this is:

In [41]:
result = zero(u) # gets vector of zeros identical in dimension to that of u
result[1] = u[1] + v[1]
result[2] = u[2] + v[2]
result[3] = u[3] + v[3]
[u v result]

3×3 Array{Int64,2}:
 10  1  11
  2  2   4
  3  3   6

##### Using loop:

In [42]:
result = zero(u)
for i=1:size(u,1)
    result[i] = u[i] + v[i]
end
[u v result]

3×3 Array{Int64,2}:
 10  1  11
  2  2   4
  3  3   6

#### Sum of elements in v

In [43]:
mySum = 0.0
for i = v
    mySum += i
end
mySum

6.0

#### Get vector of squared values in v 

#### These are called list comprehensions

In [44]:
[i^2 for i in v]

3-element Array{Int64,1}:
 1
 4
 9

#### Get vector of square-roots of positive values in x

In [45]:
x = randn(10)
[sqrt(i) for i in x if i >= 0.0]

7-element Array{Float64,1}:
 0.6411782516009619
 0.6395820245901435
 0.7820927830139083
 0.6127441976402896
 1.461359510606042 
 0.7879687702714473
 1.2398372474898554

In [46]:
x = randn(10)
res = [[i sqrt(value)] for (i,value) in enumerate(x) if value >= 0.0]

6-element Array{Array{Float64,2},1}:
 [2.0 0.843784] 
 [3.0 1.2851]   
 [6.0 0.72522]  
 [7.0 0.676749] 
 [9.0 1.80498]  
 [10.0 0.632302]

#### Matrix from res

In [47]:
resMat = [row[i] for row in res, i=1:2]

6×2 Array{Float64,2}:
  2.0  0.843784
  3.0  1.2851  
  6.0  0.72522 
  7.0  0.676749
  9.0  1.80498 
 10.0  0.632302

#### This list comprehension produces a two-dimensional array (a matrix)

In [48]:
[i+j for i=1:2, j=3:5]

2×3 Array{Int64,2}:
 4  5  6
 5  6  7

### Use of Range

In [49]:
?range

search: range LinRange UnitRange StepRange StepRangeLen StudentizedRange



```
range(start[, stop]; length, stop, step=1)
```

Given a starting value, construct a range either by length or from `start` to `stop`, optionally with a given step (defaults to 1, a [`UnitRange`](@ref)). One of `length` or `stop` is required.  If `length`, `stop`, and `step` are all specified, they must agree.

If `length` and `stop` are provided and `step` is not, the step size will be computed automatically such that there are `length` linearly spaced elements in the range (a [`LinRange`](@ref)).

If `step` and `stop` are provided and `length` is not, the overall range length will be computed automatically such that the elements are `step` spaced (a [`StepRange`](@ref)).

`stop` may be specified as either a positional or keyword argument.

!!! compat "Julia 1.1"
    `stop` as a positional argument requires at least Julia 1.1.


# Examples

```jldoctest
julia> range(1, length=100)
1:100

julia> range(1, stop=100)
1:100

julia> range(1, step=5, length=100)
1:5:496

julia> range(1, step=5, stop=100)
1:5:96

julia> range(1, 10, length=101)
1.0:0.09:10.0

julia> range(1, 100, step=5)
1:5:96
```


In [50]:
r = range(0, step=0.1, stop=1)

0.0:0.1:1.0

In [51]:
# This works too

r = 0:0.1:1

0.0:0.1:1.0

r is not an arryay, but in many contexts behaves like one

In [52]:
sin.(r)

11-element Array{Float64,1}:
 0.0                
 0.09983341664682815
 0.19866933079506122
 0.29552020666133955
 0.3894183423086505 
 0.479425538604203  
 0.5646424733950354 
 0.644217687237691  
 0.7173560908995228 
 0.7833269096274834 
 0.8414709848078965 

### Use of Map to apply a function to elements of array

In [53]:
map(sin,r)

11-element Array{Float64,1}:
 0.0                
 0.09983341664682815
 0.19866933079506122
 0.29552020666133955
 0.3894183423086505 
 0.479425538604203  
 0.5646424733950354 
 0.644217687237691  
 0.7173560908995228 
 0.7833269096274834 
 0.8414709848078965 

### Reduce and Map-Reduce

In [54]:
# sum of elements in u
reduce(+,u)

15

In [55]:
# product of elements in u
reduce(*,u)

60

In [56]:
reduce(+,1:1000000)

500000500000

#### Sum of squares

In [57]:
n = 1_000_000
mapreduce(x -> x^2, +, 1:n)

333333833333500000

#### Here, a vector of squares is created first, which, as will be demonstrated later, slower because of the time used for memory allocation

In [58]:
reduce(+,(1:n).^2)

333333833333500000

## Types

### Determine the type of a variable as:

In [59]:
# type of M
typeof(M)

Array{Int64,2}

In [60]:
# type of v
typeof(v)

Array{Int64,1}

### Composite Types

In [61]:
# Example
mutable struct BankAccount
    accountNumber::Int64
    firstName::String
    lastName::String
    balance::Float64
end

#### Get all the names in a composite type:

In [62]:
fieldnames(BankAccount)

(:accountNumber, :firstName, :lastName, :balance)

#### Get the types of all fields:

In [63]:
BankAccount.types

svec(Int64, String, String, Float64)

#### Create an instance of `BankAccount`

In [64]:
a1 = BankAccount(1234,"Tom","Smith",1000.0)
a2 = BankAccount(4321,"Jim","Shanks",500.0)
a3 = BankAccount(9321,"Scott","Williams",500.0)

BankAccount(9321, "Scott", "Williams", 500.0)

#### Access field in composite type:

In [65]:
a1.balance

1000.0

In [66]:
# can modify fields of mutable structs
a1.balance = 2000.50

2000.5

In [67]:
a2.balance

500.0

In [68]:
a2.firstName

"Jim"

## Dictionaries (Associative Arrays) 
A collection of key value pairs

### Declaration

In [69]:
# d is an empty dictionary that can store "BackAccounts" with an interger key (i.e., with the account number as the key)
d = Dict{Int64,BankAccount}()

Dict{Int64,BankAccount} with 0 entries

### Putting values in dictionary

In [70]:
d[a1.accountNumber] = a1
d

Dict{Int64,BankAccount} with 1 entry:
  1234 => BankAccount(1234, "Tom", "Smith", 2000.5)

In [71]:
d[a2.accountNumber] = a2
d

Dict{Int64,BankAccount} with 2 entries:
  4321 => BankAccount(4321, "Jim", "Shanks", 500.0)
  1234 => BankAccount(1234, "Tom", "Smith", 2000.5)

In [72]:
d[a3.accountNumber] = a3
d

Dict{Int64,BankAccount} with 3 entries:
  4321 => BankAccount(4321, "Jim", "Shanks", 500.0)
  9321 => BankAccount(9321, "Scott", "Williams", 500.0)
  1234 => BankAccount(1234, "Tom", "Smith", 2000.5)

#### Get array of keys in d

In [73]:
collect(keys(d))

3-element Array{Int64,1}:
 4321
 9321
 1234

#### Get the value associated with `key = 1234`

In [74]:
d[1234]

BankAccount(1234, "Tom", "Smith", 2000.5)

#### Get array of values in d

In [75]:
values(d)

Base.ValueIterator for a Dict{Int64,BankAccount} with 3 entries. Values:
  BankAccount(4321, "Jim", "Shanks", 500.0)
  BankAccount(9321, "Scott", "Williams", 500.0)
  BankAccount(1234, "Tom", "Smith", 2000.5)

In [76]:
collect(values(d))

3-element Array{BankAccount,1}:
 BankAccount(4321, "Jim", "Shanks", 500.0)    
 BankAccount(9321, "Scott", "Williams", 500.0)
 BankAccount(1234, "Tom", "Smith", 2000.5)    

#### Using list comprehension

In [77]:
[i for i in values(d)]

3-element Array{BankAccount,1}:
 BankAccount(4321, "Jim", "Shanks", 500.0)    
 BankAccount(9321, "Scott", "Williams", 500.0)
 BankAccount(1234, "Tom", "Smith", 2000.5)    

In [78]:
keys(d)

Base.KeySet for a Dict{Int64,BankAccount} with 3 entries. Keys:
  4321
  9321
  1234

In [79]:
[d[i] for i in keys(d)] 

3-element Array{BankAccount,1}:
 BankAccount(4321, "Jim", "Shanks", 500.0)    
 BankAccount(9321, "Scott", "Williams", 500.0)
 BankAccount(1234, "Tom", "Smith", 2000.5)    

#### Check if Dictionary has a particular key

In [80]:
haskey(d,1234)

true

In [81]:
haskey(d,123)

false

## Functions and Scope of Variables

Functions allow code to be reused. We have seen how a loop can be used to add two vectors:

In [82]:
u = [1,2]
v = [3,4]
result = zero(u)
for i=1:size(u,1)
    result[i] = u[i] + v[i]
end
[u v result]

2×3 Array{Int64,2}:
 1  3  4
 2  4  6

Suppose we now want to add vector `x` to vector `y`:

In [83]:
x = [9,7,6,5]
y = [2,2,2,1];

We can do by copying the code from above as:

In [84]:
u = x
v = y
result = zero(u)
for i=1:size(u,1)
    result[i] = u[i] + v[i]
end
[u v result]

4×3 Array{Int64,2}:
 9  2  11
 7  2   9
 6  2   8
 5  1   6

This can and should be avoided by using a function with the code that was repeated. 

In [85]:
function addVectors(u,v)
    if size(u,1) != size(v,1)
        println("The size of u (= $(size(u,1))) is not equal to the size of v (= $(size(v,1))) ")
        return []
    end
    result = zero(u)
    for i=1:size(u,1)
        result[i] = u[i] + v[i]
    end
    return result
end

addVectors (generic function with 1 method)

In [86]:
[u v addVectors(u,v)]

4×3 Array{Int64,2}:
 9  2  11
 7  2   9
 6  2   8
 5  1   6

In [87]:
[x y addVectors(x,y)]

4×3 Array{Int64,2}:
 9  2  11
 7  2   9
 6  2   8
 5  1   6

In [88]:
u

4-element Array{Int64,1}:
 9
 7
 6
 5

In [89]:
addVectors(x,u)

4-element Array{Int64,1}:
 18
 14
 12
 10

### Scope of Variables

Note that within the function `addVectors`, the output is the sum of the vectors`u` and `v`, but calling it with the vectors `x` and `y` results their sum. The variables `u` and `v` within the function refer to those given when the function was called. Thus, the same function can be used to add any two vectors of the same length. The behavior of the variables `u` and `v` with the function has to do with what is called the scope of variables and how variables are passed to functions. In Julia variables are passed "by reference" rather than "by value". This makes passing large structures to functions very efficient compared to passing arguments to the function "by value", which requies making a copy of the argument.  

However, at first, the way functions behave can be confusing as shown below. 

In [90]:
function addOne(x) # x is a local variable pointing to the value of the argument of the function 
    @show(x) 
    x = x + 1     # x is now redirected to point the the value of (x+1)
    @show(x)
    return x
end

addOne (generic function with 1 method)

In [91]:
y = 2
@show(y)
@show(addOne(y))
@show(y);             # y is still pointing to 2

y = 2
x = 2
x = 3
addOne(y) = 3
y = 2


In [92]:
function addOneToVec(x) # x is a local variable pointing to the vector argument of the function 
    @show(x) 
    x = x .+ 1          # x is now redirected to point a new vector with the values of (x+1)
    @show(x)
    return x
end    

addOneToVec (generic function with 1 method)

In [93]:
u = [1,2]
@show(u)
@show(addOneToVec(u))
@show(u)

u = [1, 2]
x = [1, 2]
x = [2, 3]
addOneToVec(u) = [2, 3]
u = [1, 2]


2-element Array{Int64,1}:
 1
 2

Compare the behavior of the following funtion with that above:

In [94]:
function addOneToVec!(x) # x is a local variable pointing to the vector argument of the function 
    @show(x) 
    x  .= x .+ 1          # x still points to the same vector, but the elemets in the vector are modified
    @show(x)
    return x
end    

addOneToVec! (generic function with 1 method)

In [95]:
u = [1,2]
@show(u)
@show(addOneToVec!(u))
@show(u)

u = [1, 2]
x = [1, 2]
x = [2, 3]
addOneToVec!(u) = [2, 3]
u = [2, 3]


2-element Array{Int64,1}:
 2
 3

In [96]:
function addOneToVecLoop!(x) # x is a local variable pointing to the vector argument of the function 
    @show(x)
    for i in 1:size(x,1)
        x[i] += 1 # x still points to the same vector, but the elemets in the vector x are are modified here
    end
    @show(x)
    return x
end    

addOneToVecLoop! (generic function with 1 method)

In [97]:
u = [1,2]
@show(u)
@show(addOneToVecLoop!(u))
@show(u)

u = [1, 2]
x = [1, 2]
x = [2, 3]
addOneToVecLoop!(u) = [2, 3]
u = [2, 3]


2-element Array{Int64,1}:
 2
 3

Nice explanation of the difference in bahavior of these functions is given here: [The Map is Not the Territory!](http://www.johnmyleswhite.com/notebook/2014/09/06/values-vs-bindings-the-map-is-not-the-territory/)

#### Functions can have arguments with default values

In [98]:
function addYToVec!(x,y=1) # x is a local variable pointing to the vector argument of the function 
    @show(x) 
    x .= x .+ y          # x still points to the same vector, but the elemets in the vector are modified
    @show(x)
    return x
end    

addYToVec! (generic function with 2 methods)

In [99]:
u = [1,2]
@show(u)
@show(addYToVec!(u))
@show(u)

u = [1, 2]
x = [1, 2]
x = [2, 3]
addYToVec!(u) = [2, 3]
u = [2, 3]


2-element Array{Int64,1}:
 2
 3

In [100]:
u = [1,2]
@show(u)
@show(addYToVec!(u,2))
@show(u)

u = [1, 2]
x = [1, 2]
x = [3, 4]
addYToVec!(u, 2) = [3, 4]
u = [3, 4]


2-element Array{Int64,1}:
 3
 4

In [101]:
function addkTimesYToVec!(x,k=1,y=2) # x is a local variable pointing to the vector argument of the function 
    @show(x) 
    x .= x .+ y*k          # x still points to the same vector, but the elemets in the vector are modified
    @show(x)
    return x
end    

addkTimesYToVec! (generic function with 3 methods)

In [102]:
u = [1,2]
@show(u)
@show(addkTimesYToVec!(u))
@show(u)

u = [1, 2]
x = [1, 2]
x = [3, 4]
addkTimesYToVec!(u) = [3, 4]
u = [3, 4]


2-element Array{Int64,1}:
 3
 4

In [103]:
addkTimesYToVec!(u,2,2)

x = [3, 4]
x = [7, 8]


2-element Array{Int64,1}:
 7
 8

###  Functions with key value pairs

In [104]:
function addcxToV!(v;c=1,x=2)
    v .= c*x .+ v
end

addcxToV! (generic function with 1 method)

In [105]:
v = [2,5]
@show(addcxToV!(v))

addcxToV!(v) = [4, 7]


2-element Array{Int64,1}:
 4
 7

In [106]:
v = [2,5]
@show(addcxToV!(v,x=1))

addcxToV!(v, x=1) = [3, 6]


2-element Array{Int64,1}:
 3
 6

### Multiple Dispatch of "+" Operator (Overloading Operators)

What the "+" operator does depends on the arguments. The function defined below will be called when it is used with two BankAccount arguments. Other operators can be similarly "overloaded" to work with user-defined types.

In [107]:
import Base.+
function +(a1::BankAccount,a2::BankAccount)
    a1.balance += a2.balance
    a2.balance = 0
end

+ (generic function with 188 methods)

In [108]:
@show(a1,a2)
a1 + a2
@show(a1,a2)

a1 = BankAccount(1234, "Tom", "Smith", 2000.5)
a2 = BankAccount(4321, "Jim", "Shanks", 500.0)
a1 = BankAccount(1234, "Tom", "Smith", 2500.5)
a2 = BankAccount(4321, "Jim", "Shanks", 0.0)


BankAccount(4321, "Jim", "Shanks", 0.0)

In [109]:
@show(a1,a2)
+(a1,a2)
@show(a1,a2)

a1 = BankAccount(1234, "Tom", "Smith", 2500.5)
a2 = BankAccount(4321, "Jim", "Shanks", 0.0)
a1 = BankAccount(1234, "Tom", "Smith", 2500.5)
a2 = BankAccount(4321, "Jim", "Shanks", 0.0)


BankAccount(4321, "Jim", "Shanks", 0.0)

### Often loops faster than vectorizng!

In [110]:
function f1(n)
    mapreduce(x -> x^2, +, 1:n)
end

f1 (generic function with 1 method)

In [111]:
function f2(n)
    reduce(+,(1:n).^2)
end

f2 (generic function with 1 method)

In [112]:
@time f1(1_000_000)

  0.046002 seconds (102.91 k allocations: 5.266 MiB)


333333833333500000

In [113]:
@time f2(1_000_000)

  0.036653 seconds (56.22 k allocations: 10.305 MiB)


333333833333500000

In [114]:
function f3(n)
    sum = 0
    for i=1:n
        sum += i^2
    end
    return sum
end    

f3 (generic function with 1 method)

In [115]:
@time f3(1_000_000)

  0.010452 seconds (13.03 k allocations: 694.286 KiB)


333333833333500000

## Exercise 1

* Write a function that uses loops to get the sum of two matrices.

* Write a function with two matrix arguments that adds the second matrix to the first. 

* Write a function that uses loops to get the product of two matrices.

## Reading and Writing from Files

### Text Files

In [9]:
using Printf # needed for formatted print commands

In [4]:
A = randn(5,3)

5×3 Array{Float64,2}:
  0.29337    -1.25023    0.65265  
  0.929887   -0.693108   0.760531 
  0.788622    0.167753  -0.311804 
  0.162461    2.20369    0.0749647
 -0.0680599  -0.581849   0.391977 

In [21]:
out = open("outFile","w")
n,p = size(A)
for j=1:p
    for i=1:n
        @printf(out,"%10.5f ", A[i,j])
    end
    @printf(out,"\n")
end
close(out)

In [22]:
;cat outFile

   0.29337    0.92989    0.78862    0.16246   -0.06806 
  -1.25023   -0.69311    0.16775    2.20369   -0.58185 
   0.65265    0.76053   -0.31180    0.07496    0.39198 


In [17]:
out = open("outFile","w")
n,p = size(A)
for j=1:p
    for i=1:n
        print(out,A[i,j]," ")
    end
    print(out,"\n")
end
close(out)

In [18]:
;cat outFile

0.2933700787469783 0.9298873913607176 0.7886216037485655 0.1624609928026136 -0.0680598897436531 
-1.2502337848998206 -0.6931075657665067 0.1677533850736536 2.203692985257342 -0.581849029125006 
0.6526500166213716 0.7605311270115546 -0.3118040438680883 0.07496469891310827 0.3919771872340053 


In [23]:
out = open("outFile","w")
n,p = size(A)
for j=1:p
    for i=1:n
        @printf(out,"%10.5e ", A[i,j])
    end
    @printf(out,"\n")
end
close(out)

In [24]:
;cat outFile

2.93370e-01 9.29887e-01 7.88622e-01 1.62461e-01 -6.80599e-02 
-1.25023e+00 -6.93108e-01 1.67753e-01 2.20369e+00 -5.81849e-01 
6.52650e-01 7.60531e-01 -3.11804e-01 7.49647e-02 3.91977e-01 


In [42]:
inStream = open("outFile","r")

IOStream(<file outFile>)

In [45]:
inStream = open("outFile","r")
for line = eachline(inStream)
    println(line)
end
close(inStream)

2.93370e-01 9.29887e-01 7.88622e-01 1.62461e-01 -6.80599e-02 
-1.25023e+00 -6.93108e-01 1.67753e-01 2.20369e+00 -5.81849e-01 
6.52650e-01 7.60531e-01 -3.11804e-01 7.49647e-02 3.91977e-01 


In [48]:
B = Array{Float64,2}(undef,5,3)

5×3 Array{Float64,2}:
 NaN            6.9296e-310   6.9296e-310
   0.0          6.9296e-310   0.0        
   1.4822e-323  5.92879e-323  6.9296e-310
   6.9296e-310  5.43472e-323  6.9296e-310
   6.9296e-310  6.9296e-310   6.9296e-310

In [52]:
B = zeros(5,3)

5×3 Array{Float64,2}:
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0

In [53]:
inStream = open("outFile","r")
j = 1
for line = eachline(inStream)
    B[:,j] = parse.(Float64,split(line))
    j += 1
end
close(inStream)

In [54]:
B

5×3 Array{Float64,2}:
  0.29337    -1.25023    0.65265  
  0.929887   -0.693108   0.760531 
  0.788622    0.167753  -0.311804 
  0.162461    2.20369    0.0749647
 -0.0680599  -0.581849   0.391977 

In [55]:
;cat outFile

2.93370e-01 9.29887e-01 7.88622e-01 1.62461e-01 -6.80599e-02 
-1.25023e+00 -6.93108e-01 1.67753e-01 2.20369e+00 -5.81849e-01 
6.52650e-01 7.60531e-01 -3.11804e-01 7.49647e-02 3.91977e-01 


### Binary Files

Write matrix A. In Julia matrices are stored by column (column-major). So should writing should be done by column.

In [75]:
binOut = open("out.bin","w")
n,p = size(A)
write(binOut,n,p)
for j=1:p, i=1:n
    write(binOut,A[i,j])
end
close(binOut)

In [76]:
binIn = open("out.bin","r")

IOStream(<file out.bin>)

#### Reading from a binary file is easy.

In [77]:
mySize = zeros(Int64,2)
read!(binIn,mySize)
C = zeros(n,p)
read!(binIn,C)
close(binIn)

In [81]:
C

5×3 Array{Float64,2}:
  0.29337    -1.25023    0.65265  
  0.929887   -0.693108   0.760531 
  0.788622    0.167753  -0.311804 
  0.162461    2.20369    0.0749647
 -0.0680599  -0.581849   0.391977 