# Fast Track to Julia NoteBook

Expanding on parts of [Fast Track to Julia](https://juliadocs.github.io/Julia-Cheat-Sheet/)

## Basics

In [1]:
a = 2.5
5a

12.5

In [2]:
5*a

12.5

`ans` has the result from the last calculation:

In [3]:
ans

12.5

### Two types of comments 

#### Frist type:

In [4]:
# this is a one line comment
9a # comment can be at the end of a line too

22.5

#### Second type:

In [5]:
#= This is the first line of a comment block
9a # comment can be at the end of a line too
This is the last line of the block =# 

### Julia allows simple way to swap values of variables

In [6]:
a,b = 1,2
[a,b]

2-element Array{Int64,1}:
 1
 2

In [7]:
# easy swapping of values
a,b = b,a
[a,b]

2-element Array{Int64,1}:
 2
 1

In [8]:
# in most languages you have to do
a = 1
b = 2
temp = a
a = b
b = temp
[a,b]

2-element Array{Int64,1}:
 2
 1

### Julia allows simple boolean expressions

In [9]:
# Example
1 < a < 3

true

In [10]:
# In many languages this has to be written as
1 < a && a < 3

true

### Ternary Operator

In [11]:
a = 1
b = 1
c = 2

res = a==b ? a : b

1

In [12]:
a==c ? a : c

2

In [13]:
a==c ? 1 : 10

10

In [14]:
a==c-b ? 1 : 10

1

### Remainder

In [15]:
99 % 10

9

In [16]:
100 % 10

0

In [17]:
90 % 10

0

## Arrays (Vectors and Matricies)

### Declaration and Initialization of arrays

In [18]:
# empty vector of double precision floats
v = Array{Float64,1}()

0-element Array{Float64,1}

In [19]:
push!(v,2.0)
v

1-element Array{Float64,1}:
 2.0

In [20]:
# vector of size 5, double precision floats
u =  Array{Float64,1}(undef, 5)

5-element Array{Float64,1}:
 0.0
 0.0
 0.0
 0.0
 0.0

In [21]:
# matrix of size 3x5, double precision floats
U =  Array{Float64,2}(undef, 3,5)

3×5 Array{Float64,2}:
 NaN            6.9485e-310  6.9485e-310   6.9485e-310  6.9485e-310
   0.0          6.9485e-310  1.08694e-322  6.9485e-310  6.9485e-310
   1.4822e-323  6.9485e-310  1.03754e-322  0.0          6.9485e-310

In [22]:
# vector of size 5, of 2.2
u =  fill(2.2,5)

5-element Array{Float64,1}:
 2.2
 2.2
 2.2
 2.2
 2.2

In [23]:
zeros(5)

5-element Array{Float64,1}:
 0.0
 0.0
 0.0
 0.0
 0.0

In [24]:
zeros(3,5)

3×5 Array{Float64,2}:
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0

In [25]:
zero(U)

3×5 Array{Float64,2}:
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0

In [26]:
ones(3,5)

3×5 Array{Float64,2}:
 1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0

In [27]:
using Random, Statistics

In [28]:
rand(3,5) # uniform(0,1)

3×5 Array{Float64,2}:
 0.891587  0.0401357  0.91547   0.531265  0.207342
 0.693194  0.15078    0.316357  0.121536  0.89916 
 0.765814  0.203055   0.152499  0.15561   0.007035

In [29]:
randn(3,5) # standard normal

3×5 Array{Float64,2}:
 0.179615    1.64913    1.34856    -1.0603     -2.41706 
 0.439123    0.186215   0.0274714  -0.0233425  -0.329273
 0.0392877  -2.3129    -0.39877    -1.02568     1.47139 

In [30]:
mean(randn(1_000_000))

-0.0013217296880590175

In [31]:
var(randn(1_000_000))

1.0003505854524457

In [32]:
using Distributions, LinearAlgebra

In [33]:
M = rand(Binomial(2,0.5),10,20)

10×20 Array{Int64,2}:
 2  0  2  0  1  1  2  1  0  0  2  1  2  2  1  0  2  1  0  0
 1  0  0  2  1  1  1  1  1  1  1  2  0  2  1  2  2  1  1  2
 0  2  0  1  1  1  1  0  1  2  2  2  1  0  1  1  1  0  1  2
 1  1  2  0  1  1  2  0  2  1  1  2  1  0  2  1  2  1  0  2
 2  1  1  0  1  1  1  0  1  2  2  1  0  1  2  1  1  0  1  1
 0  2  1  1  1  1  1  1  1  0  0  2  1  2  2  1  1  1  2  1
 1  0  2  1  2  1  1  1  2  2  1  1  0  1  2  0  1  2  0  1
 1  2  1  0  1  1  1  0  1  2  1  2  2  1  1  2  0  1  0  1
 0  2  2  1  1  1  1  2  0  2  1  2  1  1  1  1  0  2  1  2
 1  1  1  0  2  1  0  0  0  2  2  1  0  1  1  0  1  2  1  2

#### Get first column as one dimensionsal array

In [34]:
M[:,1]

10-element Array{Int64,1}:
 2
 1
 0
 1
 2
 0
 1
 1
 0
 1

#### Get first row as one dimensionsal array¶

In [35]:
M[1,:]

20-element Array{Int64,1}:
 2
 0
 2
 0
 1
 1
 2
 1
 0
 0
 2
 1
 2
 2
 1
 0
 2
 1
 0
 0

#### Transposing and array gives a row vector 

In [36]:
M[1,:]'

1×20 Adjoint{Int64,Array{Int64,1}}:
 2  0  2  0  1  1  2  1  0  0  2  1  2  2  1  0  2  1  0  0

#### Sum of squares of elements in first row

In [37]:
M[1,:]'M[1,:]

34

In [38]:
M[1,:]'*M[1,:]

34

In [39]:
dot(M[1,:],M[1,:])

34

In [40]:
M[1,:].^2

20-element Array{Int64,1}:
 4
 0
 4
 0
 1
 1
 4
 1
 0
 0
 4
 1
 4
 4
 1
 0
 4
 1
 0
 0

In [41]:
sum(M[1,:].^2)

34

#### Matrix transpose and product 

In [42]:
M'M == M'*M

true

### Identity Matrix

#### In general

In [43]:
Matrix{Float64}(I,3,3)

3×3 Array{Float64,2}:
 1.0  0.0  0.0
 0.0  1.0  0.0
 0.0  0.0  1.0

In [44]:
Matrix{Float64}(I,3,4)

3×4 Array{Float64,2}:
 1.0  0.0  0.0  0.0
 0.0  1.0  0.0  0.0
 0.0  0.0  1.0  0.0

In [45]:
Matrix{Float64}(I,4,3)

4×3 Array{Float64,2}:
 1.0  0.0  0.0
 0.0  1.0  0.0
 0.0  0.0  1.0
 0.0  0.0  0.0

#### When dimensions can be inferred

In [46]:
A = M'M + I

20×20 Array{Int64,2}:
 14   6  12   3  11   9  11   4   8  …  12   7  11  13   7  12   9   4  10
  6  20  12   6  12  11  11   6   9     20  11  10  15  12   8  11  10  17
 12  12  21   5  15  12  15   9  11     18  11  13  18   8  13  16   6  15
  3   6   5   9   7   6   6   6   6     11   3   8   8   7   7   7   6  10
 11  12  15   7  17  12  12   7  11     18   8  13  17   9  13  15   8  17
  9  11  12   6  12  11  11   6   9  …  16   8  11  14   9  11  11   7  14
 11  11  15   6  12  11  16   7  11     18  11  12  16  10  14  11   6  14
  4   6   9   6   7   6   7   9   4     10   5   9   8   5   6   9   5   8
  8   9  11   6  11   9  11   4  14     15   6   8  15   9  11   9   5  13
 12  17  16   8  18  14  13   7  13     22   9  12  19  13  12  16   9  22
 14  13  15   6  16  13  14   6  10  …  19  10  13  17  10  15  13   8  18
 12  20  18  11  18  16  18  10  15     29  14  17  22  17  17  17  12  24
  7  11  11   3   8   8  11   5   6     14  13   9  10   8   8   8   4   9
 11

### Diagonal Matrix from $\mathbf{A}$

In [47]:
Diagonal(A)

20×20 Diagonal{Int64,Array{Int64,1}}:
 14   ⋅   ⋅  ⋅   ⋅   ⋅   ⋅  ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅
  ⋅  20   ⋅  ⋅   ⋅   ⋅   ⋅  ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅
  ⋅   ⋅  21  ⋅   ⋅   ⋅   ⋅  ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅
  ⋅   ⋅   ⋅  9   ⋅   ⋅   ⋅  ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅
  ⋅   ⋅   ⋅  ⋅  17   ⋅   ⋅  ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅
  ⋅   ⋅   ⋅  ⋅   ⋅  11   ⋅  ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅
  ⋅   ⋅   ⋅  ⋅   ⋅   ⋅  16  ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅
  ⋅   ⋅   ⋅  ⋅   ⋅   ⋅   ⋅  9   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅
  ⋅   ⋅   ⋅  ⋅   ⋅   ⋅   ⋅  ⋅  14   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅
  ⋅   ⋅   ⋅  ⋅   ⋅   ⋅   ⋅  ⋅   ⋅  27   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅
  ⋅   ⋅   ⋅  ⋅   ⋅   ⋅   ⋅  ⋅   ⋅   ⋅  22   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅
  ⋅   ⋅   ⋅  ⋅   ⋅   ⋅   ⋅  ⋅   ⋅   ⋅   ⋅  29   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅
  ⋅   ⋅   ⋅  ⋅   ⋅   ⋅   ⋅

### Subset of Matrix

In [48]:
B = A[1:2,3:4]

2×2 Array{Int64,2}:
 12  3
 12  6

In [49]:
C = A[1:2,11:end]

2×10 Array{Int64,2}:
 14  12   7  11  13   7  12   9   4  10
 13  20  11  10  15  12   8  11  10  17

### Concatenation
#### Horizontal

In [50]:
[B C]

2×12 Array{Int64,2}:
 12  3  14  12   7  11  13   7  12   9   4  10
 12  6  13  20  11  10  15  12   8  11  10  17

In [51]:
hcat(B,C)

2×12 Array{Int64,2}:
 12  3  14  12   7  11  13   7  12   9   4  10
 12  6  13  20  11  10  15  12   8  11  10  17

#### Vertical

In [52]:
[ 
A[1:2,:]
A[11:end,:]
]

12×20 Array{Int64,2}:
 14   6  12   3  11   9  11   4   8  …  12   7  11  13   7  12   9   4  10
  6  20  12   6  12  11  11   6   9     20  11  10  15  12   8  11  10  17
 14  13  15   6  16  13  14   6  10     19  10  13  17  10  15  13   8  18
 12  20  18  11  18  16  18  10  15     29  14  17  22  17  17  17  12  24
  7  11  11   3   8   8  11   5   6     14  13   9  10   8   8   8   4   9
 11  10  13   8  13  11  12   9   8  …  17   9  18  15  10  13  13   9  13
 13  15  18   8  17  14  16   8  15     22  10  15  23  12  16  15  10  19
  7  12   8   7   9   9  10   5   9     17   8  10  12  14   9   8   7  14
 12   8  13   7  13  11  14   6  11     17   8  13  16   9  18  11   7  15
  9  11  16   7  15  11  11   9   9     17   8  13  15   8  11  18   7  16
  4  10   6   6   8   7   6   5   5  …  12   4   9  10   7   7   7  10  11
 10  17  15  10  17  14  14   8  13     24   9  13  19  14  15  16  11  25

In [53]:
vcat(A[1:2,:],A[11:end,:])

12×20 Array{Int64,2}:
 14   6  12   3  11   9  11   4   8  …  12   7  11  13   7  12   9   4  10
  6  20  12   6  12  11  11   6   9     20  11  10  15  12   8  11  10  17
 14  13  15   6  16  13  14   6  10     19  10  13  17  10  15  13   8  18
 12  20  18  11  18  16  18  10  15     29  14  17  22  17  17  17  12  24
  7  11  11   3   8   8  11   5   6     14  13   9  10   8   8   8   4   9
 11  10  13   8  13  11  12   9   8  …  17   9  18  15  10  13  13   9  13
 13  15  18   8  17  14  16   8  15     22  10  15  23  12  16  15  10  19
  7  12   8   7   9   9  10   5   9     17   8  10  12  14   9   8   7  14
 12   8  13   7  13  11  14   6  11     17   8  13  16   9  18  11   7  15
  9  11  16   7  15  11  11   9   9     17   8  13  15   8  11  18   7  16
  4  10   6   6   8   7   6   5   5  …  12   4   9  10   7   7   7  10  11
 10  17  15  10  17  14  14   8  13     24   9  13  19  14  15  16  11  25

### Sorting

In [54]:
sort(M[:,1])

10-element Array{Int64,1}:
 0
 0
 0
 1
 1
 1
 1
 1
 2
 2

In [55]:
index = sortperm(M[:,1])

10-element Array{Int64,1}:
  3
  6
  9
  2
  4
  7
  8
 10
  1
  5

In [56]:
M[index,1]

10-element Array{Int64,1}:
 0
 0
 0
 1
 1
 1
 1
 1
 2
 2

### Sorting the entire matrix by the first column

In [57]:
M[index,:]

10×20 Array{Int64,2}:
 0  2  0  1  1  1  1  0  1  2  2  2  1  0  1  1  1  0  1  2
 0  2  1  1  1  1  1  1  1  0  0  2  1  2  2  1  1  1  2  1
 0  2  2  1  1  1  1  2  0  2  1  2  1  1  1  1  0  2  1  2
 1  0  0  2  1  1  1  1  1  1  1  2  0  2  1  2  2  1  1  2
 1  1  2  0  1  1  2  0  2  1  1  2  1  0  2  1  2  1  0  2
 1  0  2  1  2  1  1  1  2  2  1  1  0  1  2  0  1  2  0  1
 1  2  1  0  1  1  1  0  1  2  1  2  2  1  1  2  0  1  0  1
 1  1  1  0  2  1  0  0  0  2  2  1  0  1  1  0  1  2  1  2
 2  0  2  0  1  1  2  1  0  0  2  1  2  2  1  0  2  1  0  0
 2  1  1  0  1  1  1  0  1  2  2  1  0  1  2  1  1  0  1  1

### Sorting matrix by the sum of columns 1 and 2

In [58]:
M[sortperm( M[:,1]+M[:,2] ),:]

10×20 Array{Int64,2}:
 1  0  0  2  1  1  1  1  1  1  1  2  0  2  1  2  2  1  1  2
 1  0  2  1  2  1  1  1  2  2  1  1  0  1  2  0  1  2  0  1
 2  0  2  0  1  1  2  1  0  0  2  1  2  2  1  0  2  1  0  0
 0  2  0  1  1  1  1  0  1  2  2  2  1  0  1  1  1  0  1  2
 1  1  2  0  1  1  2  0  2  1  1  2  1  0  2  1  2  1  0  2
 0  2  1  1  1  1  1  1  1  0  0  2  1  2  2  1  1  1  2  1
 0  2  2  1  1  1  1  2  0  2  1  2  1  1  1  1  0  2  1  2
 1  1  1  0  2  1  0  0  0  2  2  1  0  1  1  0  1  2  1  2
 2  1  1  0  1  1  1  0  1  2  2  1  0  1  2  1  1  0  1  1
 1  2  1  0  1  1  1  0  1  2  1  2  2  1  1  2  0  1  0  1

### Selecting rows or columns of matrix

#### Select rows where row sum is > 19

In [59]:
vec(sum(M,dims=2) .> 19)

10-element BitArray{1}:
  true
  true
  true
  true
  true
  true
  true
  true
  true
 false

In [60]:
M[vec(sum(M,dims=2) .> 19), :]

9×20 Array{Int64,2}:
 2  0  2  0  1  1  2  1  0  0  2  1  2  2  1  0  2  1  0  0
 1  0  0  2  1  1  1  1  1  1  1  2  0  2  1  2  2  1  1  2
 0  2  0  1  1  1  1  0  1  2  2  2  1  0  1  1  1  0  1  2
 1  1  2  0  1  1  2  0  2  1  1  2  1  0  2  1  2  1  0  2
 2  1  1  0  1  1  1  0  1  2  2  1  0  1  2  1  1  0  1  1
 0  2  1  1  1  1  1  1  1  0  0  2  1  2  2  1  1  1  2  1
 1  0  2  1  2  1  1  1  2  2  1  1  0  1  2  0  1  2  0  1
 1  2  1  0  1  1  1  0  1  2  1  2  2  1  1  2  0  1  0  1
 0  2  2  1  1  1  1  2  0  2  1  2  1  1  1  1  0  2  1  2

#### Get random subset of 5 columns from M

In [61]:
sel = sample(1:size(M,2),5,replace=false)

5-element Array{Int64,1}:
 20
 10
 11
  4
  7

In [62]:
M[:,sel]

10×5 Array{Int64,2}:
 0  0  2  0  2
 2  1  1  2  1
 2  2  2  1  1
 2  1  1  0  2
 1  2  2  0  1
 1  0  0  1  1
 1  2  1  1  1
 1  2  1  0  1
 2  2  1  1  1
 2  2  2  0  0

#### Get the remaining columns: 
#### M[:,-sel] does not work in Julia

In [63]:
setdiff(1:size(M,2),sel)

15-element Array{Int64,1}:
  1
  2
  3
  5
  6
  8
  9
 12
 13
 14
 15
 16
 17
 18
 19

In [64]:
M[:,setdiff(1:size(M,2),sel)] # not as nice as M[:,-sel]

10×15 Array{Int64,2}:
 2  0  2  1  1  1  0  1  2  2  1  0  2  1  0
 1  0  0  1  1  1  1  2  0  2  1  2  2  1  1
 0  2  0  1  1  0  1  2  1  0  1  1  1  0  1
 1  1  2  1  1  0  2  2  1  0  2  1  2  1  0
 2  1  1  1  1  0  1  1  0  1  2  1  1  0  1
 0  2  1  1  1  1  1  2  1  2  2  1  1  1  2
 1  0  2  2  1  1  2  1  0  1  2  0  1  2  0
 1  2  1  1  1  0  1  2  2  1  1  2  0  1  0
 0  2  2  1  1  2  0  2  1  1  1  1  0  2  1
 1  1  1  2  1  0  0  1  0  1  1  0  1  2  1

### View of array

In [65]:
m2 = @view M[:,2] # does not make a copy of the second column of M

10-element view(::Array{Int64,2}, :, 2) with eltype Int64:
 0
 0
 2
 1
 1
 2
 0
 2
 2
 1

In [66]:
m2[2] = 3
M

10×20 Array{Int64,2}:
 2  0  2  0  1  1  2  1  0  0  2  1  2  2  1  0  2  1  0  0
 1  3  0  2  1  1  1  1  1  1  1  2  0  2  1  2  2  1  1  2
 0  2  0  1  1  1  1  0  1  2  2  2  1  0  1  1  1  0  1  2
 1  1  2  0  1  1  2  0  2  1  1  2  1  0  2  1  2  1  0  2
 2  1  1  0  1  1  1  0  1  2  2  1  0  1  2  1  1  0  1  1
 0  2  1  1  1  1  1  1  1  0  0  2  1  2  2  1  1  1  2  1
 1  0  2  1  2  1  1  1  2  2  1  1  0  1  2  0  1  2  0  1
 1  2  1  0  1  1  1  0  1  2  1  2  2  1  1  2  0  1  0  1
 0  2  2  1  1  1  1  2  0  2  1  2  1  1  1  1  0  2  1  2
 1  1  1  0  2  1  0  0  0  2  2  1  0  1  1  0  1  2  1  2

Note that changing the value of m2[2] results in changing the second column of M. 

### Copy of array

In [67]:
v = [1, 2, 3]

3-element Array{Int64,1}:
 1
 2
 3

In [68]:
u = v
u[1] = 10
u

3-element Array{Int64,1}:
 10
  2
  3

In [69]:
v

3-element Array{Int64,1}:
 10
  2
  3

##### So, u is not just a copy of v. It is another name for v. To get a copy use:

In [70]:
v = [1, 2, 3]
u = copy(v)
u[1] = 10
u

3-element Array{Int64,1}:
 10
  2
  3

In [71]:
v

3-element Array{Int64,1}:
 1
 2
 3

## Control Flow and Loops

##### Consider adding the vectors u and v. One way to do this is:

In [72]:
result = zero(u) # gets vector of zeros identical in dimension to that of u
result[1] = u[1] + v[1]
result[2] = u[2] + v[2]
result[3] = u[3] + v[3]
[u v result]

3×3 Array{Int64,2}:
 10  1  11
  2  2   4
  3  3   6

##### Using loop:

In [73]:
result = zero(u)
for i=1:size(u,1)
    result[i] = u[i] + v[i]
end
[u v result]

3×3 Array{Int64,2}:
 10  1  11
  2  2   4
  3  3   6

#### Sum of elements in v

In [74]:
mySum = 0.0
for i = v
    mySum += i
end
mySum

6.0

#### Get vector of squared values in v 

#### These are called list comprehensions

In [75]:
[i^2 for i in v]

3-element Array{Int64,1}:
 1
 4
 9

#### Get vector of square-roots of positive values in x

In [76]:
x = randn(10)
[sqrt(i) for i in x if i >= 0.0]

5-element Array{Float64,1}:
 0.9510900693664935
 0.9783503071684033
 1.324402835181463 
 1.207718063742418 
 0.6685225808046908

In [77]:
x = randn(10)
res = [[i sqrt(value)] for (i,value) in enumerate(x) if value >= 0.0]

4-element Array{Array{Float64,2},1}:
 [2.0 0.0214465]
 [5.0 0.543579] 
 [7.0 1.19101]  
 [8.0 0.528575] 

#### Matrix from res

In [78]:
resMat = [row[i] for row in res, i=1:2]

4×2 Array{Float64,2}:
 2.0  0.0214465
 5.0  0.543579 
 7.0  1.19101  
 8.0  0.528575 

#### This list comprehension produces a two-dimensional array (a matrix)

In [79]:
[i+j for i=1:2, j=3:5]

2×3 Array{Int64,2}:
 4  5  6
 5  6  7

### Use of Range

In [80]:
r = range(0, step=0.1, stop=1)

0.0:0.1:1.0

In [81]:
# This works too

r = 0:0.1:1

0.0:0.1:1.0

r is not an arryay, but in many contexts behaves like one

In [82]:
sin.(r)

11-element Array{Float64,1}:
 0.0                
 0.09983341664682815
 0.19866933079506122
 0.29552020666133955
 0.3894183423086505 
 0.479425538604203  
 0.5646424733950354 
 0.644217687237691  
 0.7173560908995228 
 0.7833269096274834 
 0.8414709848078965 

### Use of Map to apply a function to elements of array

In [83]:
map(sin,r)

11-element Array{Float64,1}:
 0.0                
 0.09983341664682815
 0.19866933079506122
 0.29552020666133955
 0.3894183423086505 
 0.479425538604203  
 0.5646424733950354 
 0.644217687237691  
 0.7173560908995228 
 0.7833269096274834 
 0.8414709848078965 

### Reduce and Map-Reduce

In [84]:
# sum of elements in u
reduce(+,u)

15

In [85]:
# product of elements in u
reduce(*,u)

60

In [86]:
reduce(+,1:1000000)

500000500000

#### Sum of squares

In [87]:
n = 1_000_000
mapreduce(x -> x^2, +, 1:n)

333333833333500000

Here, a vector of squares is created first, which, as will be demonstrated later, slower because of the time used for memory allocation

In [88]:
reduce(+,(1:n).^2)

333333833333500000

## Types

### Determine the type of a variable as:

In [89]:
# type of M
typeof(M)

Array{Int64,2}

In [90]:
# type of v
typeof(v)

Array{Int64,1}

### Composite Types

In [91]:
# Example
mutable struct BankAccount
    accountNumber::Int64
    firstName::String
    lastName::String
    balance::Float64
end

#### Get all the names in a composite type:

In [92]:
fieldnames(BankAccount)

(:accountNumber, :firstName, :lastName, :balance)

#### Get the types of all fields:

In [93]:
BankAccount.types

svec(Int64, String, String, Float64)

#### Create an instance of `BankAccount`

In [94]:
a1 = BankAccount(1234,"Tom","Smith",1000.0)
a2 = BankAccount(4321,"Jim","Shanks",500.0)
a3 = BankAccount(9321,"Scott","Williams",500.0)

BankAccount(9321, "Scott", "Williams", 500.0)

#### Access field in composite type:

In [95]:
a1.balance

1000.0

In [96]:
# can modify fields of mutable structs
a1.balance = 2000.50

2000.5

In [97]:
a2.balance

500.0

In [98]:
a2.firstName

"Jim"

## Dictionaries (Associative Arrays) 
A collection of key value pairs

### Declaration

In [99]:
# d is an empty dictionary that can store "BackAccounts" with an interger key (i.e., with the account number as the key)
d = Dict{Int64,BankAccount}()

Dict{Int64,BankAccount} with 0 entries

### Putting values in dictionary

In [100]:
d[a1.accountNumber] = a1
d

Dict{Int64,BankAccount} with 1 entry:
  1234 => BankAccount(1234, "Tom", "Smith", 2000.5)

In [101]:
d[a2.accountNumber] = a2
d

Dict{Int64,BankAccount} with 2 entries:
  4321 => BankAccount(4321, "Jim", "Shanks", 500.0)
  1234 => BankAccount(1234, "Tom", "Smith", 2000.5)

In [102]:
d[a3.accountNumber] = a3
d

Dict{Int64,BankAccount} with 3 entries:
  4321 => BankAccount(4321, "Jim", "Shanks", 500.0)
  9321 => BankAccount(9321, "Scott", "Williams", 500.0)
  1234 => BankAccount(1234, "Tom", "Smith", 2000.5)

#### Get array of keys in d

In [103]:
collect(keys(d))

3-element Array{Int64,1}:
 4321
 9321
 1234

#### Get the value associated with `key = 1234`

In [104]:
d[1234]

BankAccount(1234, "Tom", "Smith", 2000.5)

#### Get array of values in d

In [105]:
values(d)

Base.ValueIterator for a Dict{Int64,BankAccount} with 3 entries. Values:
  BankAccount(4321, "Jim", "Shanks", 500.0)
  BankAccount(9321, "Scott", "Williams", 500.0)
  BankAccount(1234, "Tom", "Smith", 2000.5)

In [106]:
collect(values(d))

3-element Array{BankAccount,1}:
 BankAccount(4321, "Jim", "Shanks", 500.0)    
 BankAccount(9321, "Scott", "Williams", 500.0)
 BankAccount(1234, "Tom", "Smith", 2000.5)    

#### Using list comprehension

In [107]:
[i for i in values(d)]

3-element Array{BankAccount,1}:
 BankAccount(4321, "Jim", "Shanks", 500.0)    
 BankAccount(9321, "Scott", "Williams", 500.0)
 BankAccount(1234, "Tom", "Smith", 2000.5)    

In [108]:
keys(d)

Base.KeySet for a Dict{Int64,BankAccount} with 3 entries. Keys:
  4321
  9321
  1234

In [109]:
[d[i] for i in keys(d)] 

3-element Array{BankAccount,1}:
 BankAccount(4321, "Jim", "Shanks", 500.0)    
 BankAccount(9321, "Scott", "Williams", 500.0)
 BankAccount(1234, "Tom", "Smith", 2000.5)    

#### Check if Dictionary has a particular key

In [110]:
haskey(d,1234)

true

In [111]:
haskey(d,123)

false

## Functions and Scope of Variables

Functions allow code to be reused. We have seen how a loop can be used to add two vectors:

In [112]:
u = [1,2]
v = [3,4]
result = zero(u)
for i=1:size(u,1)
    result[i] = u[i] + v[i]
end
[u v result]

2×3 Array{Int64,2}:
 1  3  4
 2  4  6

Suppose we now want to add vector `x` to vector `y`:

In [113]:
x = [9,7,6,5]
y = [2,2,2,1];

We can do by copying the code from above as:

In [114]:
u = x
v = y
result = zero(u)
for i=1:size(u,1)
    result[i] = u[i] + v[i]
end
[u v result]

4×3 Array{Int64,2}:
 9  2  11
 7  2   9
 6  2   8
 5  1   6

This can and should be avoided by using a function with the code that was repeated. 

In [115]:
function addVectors(u,v)
    if size(u,1) != size(v,1)
        println("The size of u (= $(size(u,1))) is not equal to the size of v (= $(size(v,1))) ")
        return []
    end
    result = zero(u)
    for i=1:size(u,1)
        result[i] = u[i] + v[i]
    end
    return result
end

addVectors (generic function with 1 method)

In [116]:
[u v addVectors(u,v)]

4×3 Array{Int64,2}:
 9  2  11
 7  2   9
 6  2   8
 5  1   6

In [117]:
[x y addVectors(x,y)]

4×3 Array{Int64,2}:
 9  2  11
 7  2   9
 6  2   8
 5  1   6

In [118]:
u

4-element Array{Int64,1}:
 9
 7
 6
 5

In [119]:
addVectors(x,u)

4-element Array{Int64,1}:
 18
 14
 12
 10

### Scope of Variables

Note that within the function `addVectors`, the output is the sum of the vectors`u` and `v`, but calling it with the vectors `x` and `y` results their sum. The variables `u` and `v` within the function refer to those given when the function was called. Thus, the same function can be used to add any two vectors of the same length. The behavior of the variables `u` and `v` with the function has to do with what is called the scope of variables and how variables are passed to functions. In Julia variables are passed "by reference" rather than "by value". This makes passing large structures to functions very efficient compared to passing arguments to the function "by value", which requies making a copy of the argument.  

However, at first, the way functions behave can be confusing as shown below. 

In [120]:
function addOne(x) # x is a local variable pointing to the value of the argument of the function 
    @show(x) 
    x = x + 1     # x is now redirected to point the the value of (x+1)
    @show(x)
    return x
end

addOne (generic function with 1 method)

In [121]:
y = 2
@show(y)
@show(addOne(y))
@show(y);             # y is still pointing to 2

y = 2
x = 2
x = 3
addOne(y) = 3
y = 2


In [122]:
function addOneToVec(x) # x is a local variable pointing to the vector argument of the function 
    @show(x) 
    x = x .+ 1          # x is now redirected to point a new vector with the values of (x+1)
    @show(x)
    return x
end    

addOneToVec (generic function with 1 method)

In [123]:
u = [1,2]
@show(u)
@show(addOneToVec(u))
@show(u)

u = [1, 2]
x = [1, 2]
x = [2, 3]
addOneToVec(u) = [2, 3]
u = [1, 2]


2-element Array{Int64,1}:
 1
 2

Compare the behavior of the following funtion with that above:

In [124]:
function addOneToVec!(x) # x is a local variable pointing to the vector argument of the function 
    @show(x) 
    x  .= x .+ 1          # x still points to the same vector, but the elemets in the vector are modified
    @show(x)
    return x
end    

addOneToVec! (generic function with 1 method)

In [125]:
u = [1,2]
@show(u)
@show(addOneToVec!(u))
@show(u)

u = [1, 2]
x = [1, 2]
x = [2, 3]
addOneToVec!(u) = [2, 3]
u = [2, 3]


2-element Array{Int64,1}:
 2
 3

In [126]:
function addOneToVecLoop!(x) # x is a local variable pointing to the vector argument of the function 
    @show(x)
    for i in 1:size(x,1)
        x[i] += 1 # x still points to the same vector, but the elemets in the vector x are are modified here
    end
    @show(x)
    return x
end    

addOneToVecLoop! (generic function with 1 method)

In [127]:
u = [1,2]
@show(u)
@show(addOneToVecLoop!(u))
@show(u)

u = [1, 2]
x = [1, 2]
x = [2, 3]
addOneToVecLoop!(u) = [2, 3]
u = [2, 3]


2-element Array{Int64,1}:
 2
 3

Nice explanation of the difference in bahavior of these functions is given here: [The Map is Not the Territory!](http://www.johnmyleswhite.com/notebook/2014/09/06/values-vs-bindings-the-map-is-not-the-territory/)

#### Functions can have arguments with default values

In [128]:
function addYToVec!(x,y=1) # x is a local variable pointing to the vector argument of the function 
    @show(x) 
    x .= x .+ y          # x still points to the same vector, but the elemets in the vector are modified
    @show(x)
    return x
end    

addYToVec! (generic function with 2 methods)

In [129]:
u = [1,2]
@show(u)
@show(addYToVec!(u))
@show(u)

u = [1, 2]
x = [1, 2]
x = [2, 3]
addYToVec!(u) = [2, 3]
u = [2, 3]


2-element Array{Int64,1}:
 2
 3

In [130]:
u = [1,2]
@show(u)
@show(addYToVec!(u,2))
@show(u)

u = [1, 2]
x = [1, 2]
x = [3, 4]
addYToVec!(u, 2) = [3, 4]
u = [3, 4]


2-element Array{Int64,1}:
 3
 4

In [131]:
function addkTimesYToVec!(x,k=1,y=2) # x is a local variable pointing to the vector argument of the function 
    @show(x) 
    x .= x .+ y*k          # x still points to the same vector, but the elemets in the vector are modified
    @show(x)
    return x
end    

addkTimesYToVec! (generic function with 3 methods)

In [132]:
u = [1,2]
@show(u)
@show(addkTimesYToVec!(u))
@show(u)

u = [1, 2]
x = [1, 2]
x = [3, 4]
addkTimesYToVec!(u) = [3, 4]
u = [3, 4]


2-element Array{Int64,1}:
 3
 4

In [133]:
addkTimesYToVec!(u,2,2)

x = [3, 4]
x = [7, 8]


2-element Array{Int64,1}:
 7
 8

###  Functions with key value pairs

In [134]:
function addcxToV!(v;c=1,x=2)
    v .= c*x .+ v
end

addcxToV! (generic function with 1 method)

In [135]:
v = [2,5]
@show(addcxToV!(v))

addcxToV!(v) = [4, 7]


2-element Array{Int64,1}:
 4
 7

In [136]:
v = [2,5]
@show(addcxToV!(v,x=1))

addcxToV!(v, x=1) = [3, 6]


2-element Array{Int64,1}:
 3
 6

### Multiple Dispatch of "+" Operator (Overloading Operators)

What the "+" operator does depends on the arguments. The function defined below will be called when it is used with two BankAccount arguments. Other operators can be similarly "overloaded" to work with user-defined types.

In [137]:
import Base.+
function +(a1::BankAccount,a2::BankAccount)
    a1.balance += a2.balance
    a2.balance = 0
end

+ (generic function with 188 methods)

In [138]:
@show(a1,a2)
a1 + a2
@show(a1,a2)

a1 = BankAccount(1234, "Tom", "Smith", 2000.5)
a2 = BankAccount(4321, "Jim", "Shanks", 500.0)
a1 = BankAccount(1234, "Tom", "Smith", 2500.5)
a2 = BankAccount(4321, "Jim", "Shanks", 0.0)


BankAccount(4321, "Jim", "Shanks", 0.0)

In [139]:
@show(a1,a2)
+(a1,a2)
@show(a1,a2)

a1 = BankAccount(1234, "Tom", "Smith", 2500.5)
a2 = BankAccount(4321, "Jim", "Shanks", 0.0)
a1 = BankAccount(1234, "Tom", "Smith", 2500.5)
a2 = BankAccount(4321, "Jim", "Shanks", 0.0)


BankAccount(4321, "Jim", "Shanks", 0.0)

### Keyword arguments cannot be used for multiple dispatch 

See example below.

In [2]:
struct T1
    a
end
struct T2
    a
end
struct T3
    a
end

In [2]:
function f1(;a::T1=T1(1),b::T2=T2(2))
    println("called f1.1")
end
function f1(;a::T1=T1(1),b::T3=T2(2))
    println("called f1.2")
end

f1 (generic function with 1 method)

In [3]:
function f1(a::T1,b::T2)
    println("called f1.1")
end
function f1(a::T1,b::T3)
    println("called f1.2")
end

f1 (generic function with 2 methods)

Observe that there is only once version of the function `f1`. The error message below indicates that this is the second version of `f1`.

In [5]:
t1 = T1(1)
t2 = T2(2)
f1(t1,t2)

called f1.1


In [6]:
t1 = T1(1)
t3 = T3(2)
f1(t1,t3)

called f1.2


### Often loops faster than vectorizng!

In [140]:
function f1(n)
    mapreduce(x -> x^2, +, 1:n)
end

f1 (generic function with 1 method)

In [141]:
function f2(n)
    reduce(+,(1:n).^2)
end

f2 (generic function with 1 method)

In [142]:
@time f1(1_000_000)

  0.048004 seconds (102.91 k allocations: 5.265 MiB)


333333833333500000

In [143]:
@time f2(1_000_000)

  0.047766 seconds (56.24 k allocations: 10.307 MiB, 14.64% gc time)


333333833333500000

In [144]:
function f3(n)
    sum = 0
    for i=1:n
        sum += i^2
    end
    return sum
end    

f3 (generic function with 1 method)

In [145]:
@time f3(1_000_000)

  0.010154 seconds (13.03 k allocations: 694.286 KiB)


333333833333500000

## Exercise 1

* Write a function that uses loops to get the sum of two matrices.

* Write a function with two matrix arguments that adds the second matrix to the first. 

* Write a function that uses loops to get the product of two matrices.

## Reading and Writing from Files

### Text Files

In [146]:
using Printf # needed for formatted print commands

In [147]:
A = randn(5,3)

5×3 Array{Float64,2}:
 -1.36454   -0.730215   0.511909
 -0.16217    0.361452   0.853585
  0.648205  -1.3285    -1.98213 
  0.989491  -0.218195  -1.21799 
 -0.558793   1.63361   -1.03241 

In [148]:
out = open("outFile","w")
n,p = size(A)
for j=1:p
    for i=1:n
        @printf(out,"%10.5f ", A[i,j])
    end
    @printf(out,"\n")
end
close(out)

In [149]:
;cat outFile

  -1.36454   -0.16217    0.64821    0.98949   -0.55879 
  -0.73021    0.36145   -1.32850   -0.21819    1.63361 
   0.51191    0.85358   -1.98213   -1.21799   -1.03241 


In [150]:
out = open("outFile","w")
n,p = size(A)
for j=1:p
    for i=1:n
        print(out,A[i,j]," ")
    end
    print(out,"\n")
end
close(out)

In [151]:
;cat outFile

-1.3645413827449269 -0.1621697402526574 0.6482052661456125 0.9894907970324124 -0.5587933170234471 
-0.730214890198126 0.36145201399366594 -1.328499325904311 -0.21819484198405467 1.6336114932974686 
0.5119092095009403 0.8535847953855537 -1.9821267669081155 -1.217993246893501 -1.0324095323862894 


In [152]:
out = open("outFile","w")
n,p = size(A)
for j=1:p
    for i=1:n
        @printf(out,"%10.5e ", A[i,j])
    end
    @printf(out,"\n")
end
close(out)

In [153]:
;cat outFile

-1.36454e+00 -1.62170e-01 6.48205e-01 9.89491e-01 -5.58793e-01 
-7.30215e-01 3.61452e-01 -1.32850e+00 -2.18195e-01 1.63361e+00 
5.11909e-01 8.53585e-01 -1.98213e+00 -1.21799e+00 -1.03241e+00 


In [154]:
inStream = open("outFile","r")
for line = eachline(inStream)
    println(line)
end
close(inStream)

-1.36454e+00 -1.62170e-01 6.48205e-01 9.89491e-01 -5.58793e-01 
-7.30215e-01 3.61452e-01 -1.32850e+00 -2.18195e-01 1.63361e+00 
5.11909e-01 8.53585e-01 -1.98213e+00 -1.21799e+00 -1.03241e+00 


In [155]:
B = Array{Float64,2}(undef,5,3)

5×3 Array{Float64,2}:
   6.5691e-320  6.9485e-310   6.9485e-310
 NaN            6.9485e-310   0.0        
   1.4822e-323  1.58101e-322  6.9485e-310
   6.9485e-310  1.5316e-322   6.9485e-310
   6.9485e-310  6.9485e-310   6.9485e-310

In [156]:
B = zeros(5,3)

5×3 Array{Float64,2}:
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0

In [157]:
inStream = open("outFile","r")
j = 1
for line = eachline(inStream)
    B[:,j] = parse.(Float64,split(line))
    j += 1
end
close(inStream)

In [158]:
B

5×3 Array{Float64,2}:
 -1.36454   -0.730215   0.511909
 -0.16217    0.361452   0.853585
  0.648205  -1.3285    -1.98213 
  0.989491  -0.218195  -1.21799 
 -0.558793   1.63361   -1.03241 

In [159]:
;cat outFile

-1.36454e+00 -1.62170e-01 6.48205e-01 9.89491e-01 -5.58793e-01 
-7.30215e-01 3.61452e-01 -1.32850e+00 -2.18195e-01 1.63361e+00 
5.11909e-01 8.53585e-01 -1.98213e+00 -1.21799e+00 -1.03241e+00 


### Binary Files

Write matrix A. In Julia matrices are stored by column (column-major). So should writing should be done by column.

In [160]:
binOut = open("out.bin","w")
n,p = size(A)
write(binOut,n,p)
for j=1:p, i=1:n
    write(binOut,A[i,j])
end
close(binOut)

In [161]:
binIn = open("out.bin","r")

IOStream(<file out.bin>)

#### Reading from a binary file is easy.

In [162]:
mySize = zeros(Int64,2)
read!(binIn,mySize)
C = zeros(n,p)
read!(binIn,C)
close(binIn)

In [163]:
C

5×3 Array{Float64,2}:
 -1.36454   -0.730215   0.511909
 -0.16217    0.361452   0.853585
  0.648205  -1.3285    -1.98213 
  0.989491  -0.218195  -1.21799 
 -0.558793   1.63361   -1.03241 