# Fast Track to Julia NoteBook

Expanding on parts of [Fast Track to Julia](https://juliadocs.github.io/Julia-Cheat-Sheet/)

## Basics

In [1]:
a = 2.5
5a

12.5

`ans` has the result from the last calculation:

In [2]:
ans

12.5

### Two types of comments 

#### Frist type:

In [3]:
# this is a one line comment
9a # comment can be at the end of a line too

22.5

#### Second type:

In [6]:
#= This is the first line of a comment block
9a # comment can be at the end of a line too
This is the last line of the block =# 

### Julia allows simple way to swap values of variables

In [16]:
a,b = 1,2
[a,b]

2-element Array{Int64,1}:
 1
 2

In [17]:
# easy swapping of values
a,b = b,a
[a,b]

2-element Array{Int64,1}:
 2
 1

In [19]:
# in most languages you have to do
a = 1
b = 2
temp = a
a = b
b = temp
[a,b]

2-element Array{Int64,1}:
 2
 1

### Julia allows simple boolean expressions

In [7]:
# Example
1 < a < 3

true

In [11]:
# In many languages this has to be written as
1 < a && a < 3

true

### Ternary Operator

In [107]:
a = 1
b = 1
c = 2

a==b ? a : b

1

In [108]:
a==c ? a : c

2

In [109]:
a==c ? 1 : 10

10

In [110]:
a==c-b ? 1 : 10

1

### Remainder

In [112]:
99 % 10

9

In [113]:
100 % 10

0

In [114]:
90 % 10

0

## Arrays (Vectors and Matricies)

### Declaration and Initialization of arrays

In [27]:
# empty vector of double precision floats
v = Array{Float64,1}()

0-element Array{Float64,1}

In [28]:
# vector of size 5, double precision floats
u =  Array{Float64,1}(undef, 5)

5-element Array{Float64,1}:
 6.91359504686234e-310
 6.9135950468655e-310 
 6.91359504686867e-310
 6.91360239775363e-310
 6.913595046875e-310  

In [38]:
# matrix of size 3x5, double precision floats
U =  Array{Float64,2}(undef, 3,5)

3×5 Array{Float64,2}:
 NaN             6.9136e-310  6.9136e-310   6.9136e-310  6.9136e-310
   0.0           6.9136e-310  2.96439e-323  6.9136e-310  6.9136e-310
   1.97626e-323  6.9136e-310  2.47033e-323  0.0          6.9136e-310

In [30]:
# vector of size 5, of 2.2
u =  fill(2.2,5)

5-element Array{Float64,1}:
 2.2
 2.2
 2.2
 2.2
 2.2

In [31]:
zeros(5)

5-element Array{Float64,1}:
 0.0
 0.0
 0.0
 0.0
 0.0

In [39]:
zeros(3,5)

3×5 Array{Float64,2}:
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0

In [44]:
zero(U)

3×5 Array{Float64,2}:
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0

In [43]:
ones(3,5)

3×5 Array{Float64,2}:
 1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0

In [6]:
using Random, Statistics

In [5]:
rand(3,5) # uniform(0,1)

3×5 Array{Float64,2}:
 0.836156   0.0225852  0.811995  0.790841  0.310659
 0.0911435  0.26396    0.492453  0.982861  0.757131
 0.692959   0.494696   0.306638  0.265908  0.734333

In [4]:
randn(3,5) # standard normal

3×5 Array{Float64,2}:
 -0.0511797   3.54554    0.794721  -1.24687   1.39002
 -0.285867   -0.323765   0.874391  -1.89488  -1.00163
  0.261009    1.15933   -0.280448  -1.80887   1.52828

In [7]:
mean(randn(1_000_000))

-0.00033606536110902596

In [8]:
var(randn(1_000_000))

0.9996567477884062

In [9]:
using Distributions

In [11]:
M = rand(Binomial(2,0.5),10,20)

10×20 Array{Int64,2}:
 0  0  2  2  0  1  2  0  2  0  1  2  2  0  1  0  1  2  2  2
 2  1  1  0  2  2  1  1  2  1  2  1  0  2  1  1  2  0  1  0
 0  2  1  1  2  1  2  0  1  0  0  2  1  1  2  1  1  1  1  2
 1  1  0  0  1  1  0  1  1  1  0  1  1  0  0  2  1  0  1  2
 0  2  2  0  0  1  0  0  0  1  0  1  0  0  2  1  1  1  1  0
 2  1  1  1  1  1  1  1  1  1  2  0  1  1  1  1  1  2  2  1
 0  1  2  2  2  0  2  1  0  1  0  1  0  2  1  0  0  0  1  1
 2  1  2  2  1  2  1  2  0  2  1  1  2  2  0  1  1  0  1  2
 2  0  2  1  2  2  0  1  1  1  1  2  0  1  0  1  1  2  1  1
 1  1  2  0  0  1  1  2  2  1  0  1  0  0  1  0  0  2  2  1

#### Get first column as one dimensionsal array

In [53]:
M[:,1]

10-element Array{Int64,1}:
 0
 2
 0
 1
 0
 2
 0
 2
 2
 1

#### Get first row as one dimensionsal array¶

In [54]:
M[1,:]

20-element Array{Int64,1}:
 0
 0
 2
 2
 0
 1
 2
 0
 2
 0
 1
 2
 2
 0
 1
 0
 1
 2
 2
 2

#### Transposing and array gives a row vector 

In [56]:
M[1,:]'

1×20 LinearAlgebra.Adjoint{Int64,Array{Int64,1}}:
 0  0  2  2  0  1  2  0  2  0  1  2  2  0  1  0  1  2  2  2

#### Sum of squares of elements in first row

In [57]:
M[1,:]'M[1,:]

40

In [59]:
M[1,:]'*M[1,:]

40

In [61]:
M[1,:].^2

20-element Array{Int64,1}:
 0
 0
 4
 4
 0
 1
 4
 0
 4
 0
 1
 4
 4
 0
 1
 0
 1
 4
 4
 4

In [60]:
sum(M[1,:].^2)

40

#### Matrix transpose and product 

In [62]:
M'M == M'*M

true

### Identity Matrix

#### In general

In [92]:
using LinearAlgebra
Matrix{Float64}(I,3,3)

3×3 Array{Float64,2}:
 1.0  0.0  0.0
 0.0  1.0  0.0
 0.0  0.0  1.0

In [93]:
Matrix{Float64}(I,3,4)

3×4 Array{Float64,2}:
 1.0  0.0  0.0  0.0
 0.0  1.0  0.0  0.0
 0.0  0.0  1.0  0.0

In [94]:
Matrix{Float64}(I,4,3)

4×3 Array{Float64,2}:
 1.0  0.0  0.0
 0.0  1.0  0.0
 0.0  0.0  1.0
 0.0  0.0  0.0

#### When dimensions can be inferred

In [96]:
A = M'M + I

20×20 Array{Int64,2}:
 19   8  14   8  13  16   7  13  11  …  10   7  12   5  10  11  10  13  11
  8  15  14   7  11  11  10   8   8     11   6   9  12   9   9   8  12  11
 14  14  28  16  15  18  16  14  14     19  10  14  14   9  12  17  20  17
  8   7  16  16  11  10  13   8   7     12  10  11   7   5   7   9  12  14
 13  11  15  11  20  14  12  10  10     14   6  15   9  10  11   8  12  13
 16  11  18  10  14  19  10  12  13  …  15   9  12   9  11  13  12  15  14
  7  10  16  13  12  10  17   8  11     13   9  11  11   5   8  10  14  14
 13   8  14   8  10  12   8  14   9      9   6  10   5   7   7   8  12  11
 11   8  14   7  10  13  11   9  17     13   7   7   9   7  10  13  15  12
 12   9  14   8  10  12   7  11   7      9   6  10   6   8   8   7  11  10
 12   5  10   7   9  11   7   7   9  …   7   6   9   5   6   9   8  10   7
 10  11  19  12  14  15  13   9  13     19   9  10  11   9  11  13  15  16
  7   6  10  10   6   9   9   6   7      9  12   6   5   6   7   7  10  13
 12

### Subset of Matrix

In [101]:
B = A[1:2,3:4]

2×2 Array{Int64,2}:
 14  8
 14  7

In [99]:
C = A[1:2,11:end]

2×10 Array{Int64,2}:
 12  10  7  12   5  10  11  10  13  11
  5  11  6   9  12   9   9   8  12  11

### Concatenation
#### Horizontal

In [103]:
[B C]

2×12 Array{Int64,2}:
 14  8  12  10  7  12   5  10  11  10  13  11
 14  7   5  11  6   9  12   9   9   8  12  11

In [104]:
hcat(B,C)

2×12 Array{Int64,2}:
 14  8  12  10  7  12   5  10  11  10  13  11
 14  7   5  11  6   9  12   9   9   8  12  11

#### Vertical

In [105]:
[ 
A[1:2,:]
A[11:end,:]
]

12×20 Array{Int64,2}:
 19   8  14   8  13  16   7  13  11  …  10   7  12   5  10  11  10  13  11
  8  15  14   7  11  11  10   8   8     11   6   9  12   9   9   8  12  11
 12   5  10   7   9  11   7   7   9      7   6   9   5   6   9   8  10   7
 10  11  19  12  14  15  13   9  13     19   9  10  11   9  11  13  15  16
  7   6  10  10   6   9   9   6   7      9  12   6   5   6   7   7  10  13
 12   9  14  11  15  12  11  10   7  …  10   6  16   7   7   9   5  10  10
  5  12  14   7   9   9  11   5   9     11   5   7  14   6   8  10  12   9
 10   9   9   5  10  11   5   7   7      9   6   7   6  11   9   6   9  10
 11   9  12   7  11  13   8   7  10     11   7   9   8   9  12   8  11  10
 10   8  17   9   8  12  10   8  13     13   7   5  10   6   8  19  16  12
 13  12  20  12  12  15  14  12  15  …  15  10  10  12   9  11  16  20  16
 11  11  17  14  13  14  14  11  12     16  13  10   9  10  10  12  16  21

In [106]:
vcat(A[1:2,:],A[11:end,:])

12×20 Array{Int64,2}:
 19   8  14   8  13  16   7  13  11  …  10   7  12   5  10  11  10  13  11
  8  15  14   7  11  11  10   8   8     11   6   9  12   9   9   8  12  11
 12   5  10   7   9  11   7   7   9      7   6   9   5   6   9   8  10   7
 10  11  19  12  14  15  13   9  13     19   9  10  11   9  11  13  15  16
  7   6  10  10   6   9   9   6   7      9  12   6   5   6   7   7  10  13
 12   9  14  11  15  12  11  10   7  …  10   6  16   7   7   9   5  10  10
  5  12  14   7   9   9  11   5   9     11   5   7  14   6   8  10  12   9
 10   9   9   5  10  11   5   7   7      9   6   7   6  11   9   6   9  10
 11   9  12   7  11  13   8   7  10     11   7   9   8   9  12   8  11  10
 10   8  17   9   8  12  10   8  13     13   7   5  10   6   8  19  16  12
 13  12  20  12  12  15  14  12  15  …  15  10  10  12   9  11  16  20  16
 11  11  17  14  13  14  14  11  12     16  13  10   9  10  10  12  16  21

### Sorting

In [12]:
sort(M[:,1])

10-element Array{Int64,1}:
 0
 0
 0
 0
 1
 1
 2
 2
 2
 2

In [14]:
index = sortperm(M[:,1])

10-element Array{Int64,1}:
  1
  3
  5
  7
  4
 10
  2
  6
  8
  9

In [15]:
M[index,1]

10-element Array{Int64,1}:
 0
 0
 0
 0
 1
 1
 2
 2
 2
 2

### Sorting the entire matrix by the first column

In [87]:
M[index,:]

10×20 Array{Int64,2}:
 0  0  2  2  0  1  2  0  2  0  1  2  2  0  1  0  1  2  2  2
 0  2  1  1  2  1  2  0  1  0  0  2  1  1  2  1  1  1  1  2
 0  2  2  0  0  1  0  0  0  1  0  1  0  0  2  1  1  1  1  0
 0  1  2  2  2  0  2  1  0  1  0  1  0  2  1  0  0  0  1  1
 1  1  0  0  1  1  0  1  1  1  0  1  1  0  0  2  1  0  1  2
 1  1  2  0  0  1  1  2  2  1  0  1  0  0  1  0  0  2  2  1
 2  1  1  0  2  2  1  1  2  1  2  1  0  2  1  1  2  0  1  0
 2  1  1  1  1  1  1  1  1  1  2  0  1  1  1  1  1  2  2  1
 2  1  2  2  1  2  1  2  0  2  1  1  2  2  0  1  1  0  1  2
 2  0  2  1  2  2  0  1  1  1  1  2  0  1  0  1  1  2  1  1

### Sorting matrix by the sum of columns 1 and 2

In [33]:
M[sortperm( M[:,1]+M[:,2] ),:]

10×20 Array{Int64,2}:
 0  0  2  2  0  1  2  0  2  0  1  2  2  0  1  0  1  2  2  2
 0  1  2  2  2  0  2  1  0  1  0  1  0  2  1  0  0  0  1  1
 0  2  1  1  2  1  2  0  1  0  0  2  1  1  2  1  1  1  1  2
 1  1  0  0  1  1  0  1  1  1  0  1  1  0  0  2  1  0  1  2
 0  2  2  0  0  1  0  0  0  1  0  1  0  0  2  1  1  1  1  0
 2  0  2  1  2  2  0  1  1  1  1  2  0  1  0  1  1  2  1  1
 1  1  2  0  0  1  1  2  2  1  0  1  0  0  1  0  0  2  2  1
 2  1  1  0  2  2  1  1  2  1  2  1  0  2  1  1  2  0  1  0
 2  1  1  1  1  1  1  1  1  1  2  0  1  1  1  1  1  2  2  1
 2  1  2  2  1  2  1  2  0  2  1  1  2  2  0  1  1  0  1  2

### Selecting rows or columns of matrix

#### Select rows where row sum is > 19

In [52]:
vec(sum(M,dims=2) .> 19)

10-element BitArray{1}:
  true
  true
  true
 false
 false
  true
 false
  true
  true
 false

In [47]:
M[vec(sum(M,dims=2) .> 19), :]

6×20 Array{Int64,2}:
 0  0  2  2  0  1  2  0  2  0  1  2  2  0  1  0  1  2  2  2
 2  1  1  0  2  2  1  1  2  1  2  1  0  2  1  1  2  0  1  0
 0  2  1  1  2  1  2  0  1  0  0  2  1  1  2  1  1  1  1  2
 2  1  1  1  1  1  1  1  1  1  2  0  1  1  1  1  1  2  2  1
 2  1  2  2  1  2  1  2  0  2  1  1  2  2  0  1  1  0  1  2
 2  0  2  1  2  2  0  1  1  1  1  2  0  1  0  1  1  2  1  1

#### Get random subset of 5 columns from M

In [64]:
sel = sample(1:size(M,2),5,replace=false)

5-element Array{Int64,1}:
 10
  7
  1
 13
  3

In [65]:
M[:,sel]

10×5 Array{Int64,2}:
 0  2  0  2  2
 1  1  2  0  1
 0  2  0  1  1
 1  0  1  1  0
 1  0  0  0  2
 1  1  2  1  1
 1  2  0  0  2
 2  1  2  2  2
 1  0  2  0  2
 1  1  1  0  2

#### Get the remaining columns: 
#### M[:,-sel] does not work in Julia

In [85]:
setdiff(1:size(M,2),sel)

15-element Array{Int64,1}:
  2
  4
  5
  6
  8
  9
 11
 12
 14
 15
 16
 17
 18
 19
 20

In [86]:
M[:,setdiff(1:size(M,2),sel)] # not as nice as M[:,-sel]

10×15 Array{Int64,2}:
 0  2  0  1  0  2  1  2  0  1  0  1  2  2  2
 1  0  2  2  1  2  2  1  2  1  1  2  0  1  0
 2  1  2  1  0  1  0  2  1  2  1  1  1  1  2
 1  0  1  1  1  1  0  1  0  0  2  1  0  1  2
 2  0  0  1  0  0  0  1  0  2  1  1  1  1  0
 1  1  1  1  1  1  2  0  1  1  1  1  2  2  1
 1  2  2  0  1  0  0  1  2  1  0  0  0  1  1
 1  2  1  2  2  0  1  1  2  0  1  1  0  1  2
 0  1  2  2  1  1  1  2  1  0  1  1  2  1  1
 1  0  0  1  2  2  0  1  0  1  0  0  2  2  1

### Copy of array

In [121]:
v = [1, 2, 3]

3-element Array{Int64,1}:
 1
 2
 3

In [126]:
u = v
u[1] = 10
u

3-element Array{Int64,1}:
 10
  2
  3

In [127]:
v

3-element Array{Int64,1}:
 10
  2
  3

##### So, u is not just a copy of v. It is another name for v. To get a copy use:

In [128]:
v = [1, 2, 3]
u = copy(v)
u[1] = 10
u

3-element Array{Int64,1}:
 10
  2
  3

In [129]:
v

3-element Array{Int64,1}:
 1
 2
 3

## Control Flow and Loops

##### Consider adding the vectors u and v. One way to do this is:

In [132]:
result = zero(u) # gets vector of zeros identical in dimension to that of u
result[1] = u[1] + v[1]
result[2] = u[2] + v[2]
result[3] = u[3] + v[3]
[u v result]

3×3 Array{Int64,2}:
 10  1  11
  2  2   4
  3  3   6

##### Using loop:

In [133]:
result = zero(u)
for i=1:size(u,1)
    result[i] = u[i] + v[i]
end
[u v result]

3×3 Array{Int64,2}:
 10  1  11
  2  2   4
  3  3   6

#### Sum of elements in v

In [148]:
mySum = 0.0
for i = v
    mySum += i
end
mySum

6.0

#### Get vector of squared values in v 

#### These are called list comprehensions

In [135]:
[i^2 for i in v]

3-element Array{Int64,1}:
 1
 4
 9

#### Get vector of square-roots of positive values in x

In [143]:
x = randn(10)
[sqrt(i) for i in x if i > 0.0]

8-element Array{Float64,1}:
 0.887039660794614  
 1.1736737518757063 
 1.0991885314062102 
 0.5535707452062117 
 0.36075386168935675
 0.892039591970934  
 1.4243549910796944 
 0.814796994281538  

In [151]:
x = randn(10)
res = [[i sqrt(value)] for (i,value) in enumerate(x) if value > 0.0]

8-element Array{Array{Float64,2},1}:
 [1.0 0.413247] 
 [3.0 0.865288] 
 [4.0 0.668961] 
 [5.0 1.13697]  
 [7.0 1.45655]  
 [8.0 1.19631]  
 [9.0 1.26048]  
 [10.0 0.549283]

#### Matrix from res

In [152]:
resMat = [row[i] for row in res, i=1:2]

8×2 Array{Float64,2}:
  1.0  0.413247
  3.0  0.865288
  4.0  0.668961
  5.0  1.13697 
  7.0  1.45655 
  8.0  1.19631 
  9.0  1.26048 
 10.0  0.549283

#### This list comprehension produces a two-dimensional array (a matrix)

In [164]:
[i+j for i=1:2, j=3:5]

2×3 Array{Int64,2}:
 4  5  6
 5  6  7

### Use of Range

In [165]:
?range

search: range LinRange UnitRange StepRange StepRangeLen StudentizedRange



```
range(start[, stop]; length, stop, step=1)
```

Given a starting value, construct a range either by length or from `start` to `stop`, optionally with a given step (defaults to 1, a [`UnitRange`](@ref)). One of `length` or `stop` is required.  If `length`, `stop`, and `step` are all specified, they must agree.

If `length` and `stop` are provided and `step` is not, the step size will be computed automatically such that there are `length` linearly spaced elements in the range (a [`LinRange`](@ref)).

If `step` and `stop` are provided and `length` is not, the overall range length will be computed automatically such that the elements are `step` spaced (a [`StepRange`](@ref)).

`stop` may be specified as either a positional or keyword argument.

!!! compat "Julia 1.1"
    `stop` as a positional argument requires at least Julia 1.1.


# Examples

```jldoctest
julia> range(1, length=100)
1:100

julia> range(1, stop=100)
1:100

julia> range(1, step=5, length=100)
1:5:496

julia> range(1, step=5, stop=100)
1:5:96

julia> range(1, 10, length=101)
1.0:0.09:10.0

julia> range(1, 100, step=5)
1:5:96
```


In [166]:
r = range(0, step=0.1, stop=1)

0.0:0.1:1.0

In [3]:
# This works too

r = 0:0.1:1

0.0:0.1:1.0

r is not an arryay, but in many contexts behaves like one

In [163]:
sin.(r)

11-element Array{Float64,1}:
 0.0                
 0.09983341664682815
 0.19866933079506122
 0.29552020666133955
 0.3894183423086505 
 0.479425538604203  
 0.5646424733950354 
 0.644217687237691  
 0.7173560908995228 
 0.7833269096274834 
 0.8414709848078965 

### Use of Map to apply a function to elements of array

In [168]:
map(sin,r)

11-element Array{Float64,1}:
 0.0                
 0.09983341664682815
 0.19866933079506122
 0.29552020666133955
 0.3894183423086505 
 0.479425538604203  
 0.5646424733950354 
 0.644217687237691  
 0.7173560908995228 
 0.7833269096274834 
 0.8414709848078965 

### Reduce and Map-Reduce

In [176]:
# sum of elements in u
reduce(+,u)

15

In [178]:
# product of elements in u
reduce(*,u)

60

In [2]:
reduce(+,1:1000000)

500000500000

In [5]:
mapreduce(x -> x^2, +, 1:1000000)

333333833333500000